//////////////////////////////////////////////////////////////////////
// Object2VR light 4.0/20804 Object Player                          //
// License: andreas fuhrer                                          //
// (c) 2024, Garden Gnome Software, https://ggnome.com              //
//////////////////////////////////////////////////////////////////////

(()=>{class H{constructor(){this.v=this.value=0;this.Pb=-1;this.unit="px"}kc(a,b,c){let e=0;a.hasOwnProperty("value")&&(e=a.value,a.hasOwnProperty("unit")||(a.unit="px"),"px"==a.unit||"%"==a.unit)&&(this.unit!=a.unit&&(this.value="%"==a.unit?this.value/c*100:this.value*c/100),this.unit=a.unit);b&&b.hasOwnProperty("duration")&&0<b.duration||(this.value=e);this.Pb=e}rb(a,b=-1){-1==b&&(b=this.value);this.v="%"==this.unit?.01*b*a:b}Tb(a,b){-1!=this.Pb&&(this.Pb==this.value?this.rb(b):(this.rb(b,this.value+
(this.Pb-this.value)*a),1<=a&&(this.value=this.Pb)))}}class M{constructor(){this.Qd=-1E7;this.Gg=!1}}class E{Pc(a){return-99991===a?this.Ae:"4.0/20804"}Rf(){return this.Gd}eh(a){0<a&&(this.Gd=a)}Fd(a){if(""!=a)try{let b;b="object"===typeof a?a:JSON.parse(a);if("object"===typeof b)for(const c in b)if("translations"==c&&this.T.hasOwnProperty("translations")){let e=b[c];for(const m in e)if(this.T.translations.hasOwnProperty(m))for(a=0;a<e[m].length-1;a++)""!=e[m][a]&&(this.T.translations[m][a]=
e[m][a]);else this.T.translations[m]=e[m]}else this.T[c]=b[c];this.T.hasOwnProperty("projectLanguage")&&(this.Hb=this.T.projectLanguage);this.u("languagechanged",{language:this.wb})}catch(b){console.error(b)}}Ta(a,b){let c=a;if(""!=c&&"object"===typeof this.T&&this.T.hasOwnProperty("languages")&&this.T.hasOwnProperty("translations")){var e=this.T.languages.indexOf(this.wb);-1!=e&&this.T.translations.hasOwnProperty(a)&&(a=this.T.translations[a],Array.isArray(a)&&a.length>e&&""!=a[e]&&(c=a[e]))}if(b&&
0<b.length)for(e=b.length-1;0<=e;e--)c=c.replace(new RegExp("%"+String(e+1),"g"),b[e]);return c}Qe(a){this.xe=!0;a=a.replace("_","-");if("object"===typeof this.T&&this.T.hasOwnProperty("languages")&&this.T.hasOwnProperty("translations")&&this.Hb!=a){let b=-1,c=-1,e="",m=-1,q=-1,n=a.substring(0,2).toUpperCase();for(let t=0;t<this.T.languages.length;t++)if(this.T.languages[t].toUpperCase()==a.toUpperCase()){b=t;break}else if(!this.Hb.toUpperCase().startsWith(n)&&this.T.languages[t].toUpperCase().startsWith(n)){if(""==
e||-1!=e.indexOf("-"))c=t,e=this.T.languages[t]}else{let r=window.navigator.languages;for(let f=0;f<r.length;f++)!this.Hb.toUpperCase().startsWith(n)&&this.T.languages[t].toUpperCase().startsWith(r[f].substring(0,2).toUpperCase())&&(-1==q||f<q)&&(m=t,q=f)}a=-1!=b?b:-1!=c?c:m;a=-1!=a?this.T.languages[a]:this.Hb}this.wb!=a&&(this.wb=a,this.B.setAttribute("lang",a),this.u("languagechanged",{language:a}))}dg(){return this.wb}tg(){return this.Le}addListener(a,b){(this.xb[a]=this.xb[a]||[]).push(b)}u(a,
b){if(a=this.xb[a]){let c=a.length;for(let e=0;e<c;e++)try{a[e].apply(null,[b])}catch(m){this.Be(m)}}}removeEventListener(a,b){let c=this.xb[a];if(c){var e;var m=0;for(e=c.length;m<e;m++)if(c[m]===b){1===e?delete this.xb[a]:c.splice(m,1);break}}}bh(){this.D=!0}yf(a,b,c,e){if(!this.ka.hasOwnProperty(a)){let m=new M;this.ka[a]=m;m.type=b;"undefined"!==typeof c&&this.mc(a,c);"object"===typeof e&&this.Ve(a,e);return!0}return!1}static $d(a){let b=document.cookie.indexOf(a+"="),c="";-1!=b&&(b=b+a.length+
1,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),c=decodeURIComponent(document.cookie.substring(b,a)));return c}static uh(a,b){0==a.type?a.value="string"===typeof b?b:b.toString():1==a.type?a.value="string"===typeof b?parseFloat(b):"number"===typeof b?b:b?1:0:2==a.type&&(a.value="string"===typeof b?"false"!==b&&""!==b&&"0"!==b:"number"===typeof b?0!=b:!!b)}Ve(a,b){if(this.ka.hasOwnProperty(a)&&"object"===typeof b){let e=this.ka[a];b.hasOwnProperty("cookiePath")&&(e.Rd=String(b.cookiePath));
b.hasOwnProperty("cookieExpireDays")&&(e.Qd=parseFloat(b.cookieExpireDays));if(b.hasOwnProperty("keep")&&(e.$c=!!b.keep,e.$c&&0<document.cookie.length))if(""!=this.qb){if(-1!=document.cookie.indexOf(this.qb+"=")){var c=JSON.parse(E.$d(this.qb));c.hasOwnProperty(a)&&this.mc(a,c[a])}}else c="ggvar_"+a,-1!=document.cookie.indexOf(c+"=")&&(c=E.$d(c),this.mc(a,c));b.hasOwnProperty("ignoreInState")&&(e.Gg=b.ignoreInState);b.hasOwnProperty("customProperty")&&"object"===typeof b.customProperty&&(b=b.customProperty,
this.N.hasOwnProperty(a)?(this.N[a].variabletype!=b.variableType||this.N[a].propertytype!=b.propertyType)&&console.log("Custom property added as variable has different types than custom property from project."):this.N[a]={za:b.variableType,Ib:b.propertyType,Ic:b.defaultValue});return!0}return!1}th(a,b){this.qb=a;b&&"object"===typeof b&&(b.hasOwnProperty("cookiePath")&&(this.cf=String(b.cookiePath)),b.hasOwnProperty("cookieExpireDays")&&(this.bf=parseFloat(b.cookieExpireDays)))}static Hd(a,b,c){-1<=
b&&(a+="; max-age="+86400*b);""!=c&&(a+="; path="+c);return a}static ae(a,b){switch(b){case 0:return a;case 1:return a.toString();case 2:return a?"true":"false"}}static Nc(a,b){switch(b){case 0:return a;case 1:return Number(a);case 2:return"true"==a}}vg(a,b){""==a&&(a="node1");return this.tb.hasOwnProperty(a)&&this.tb[a].hasOwnProperty(b)?this.Wb(E.Nc(this.tb[a][b],this.N[b].za),this.N[b].za):null}rh(a,b,c){c="string"===typeof c?c:E.ae(c,this.N[b].za);this.tb[a][b]!=c&&(this.tb[a][b]=c,this.u("varchanged_"+
b,{}))}de(a,b,c){""==a&&(a="node1");return this.aa.hasOwnProperty(a)&&this.aa[a].hasOwnProperty(b)&&this.aa[a][b].hasOwnProperty(c)?this.Wb(E.Nc(this.aa[a][b][c],this.N[c].za),this.N[c].za):this.N.hasOwnProperty(c)?this.Wb(E.Nc(this.N[c].Ic,this.N[c].za),this.N[c].za):null}Pe(a,b,c,e){""==a&&(a="node1");e="string"===typeof e?e:E.ae(e,this.N[c].za);this.aa.hasOwnProperty(a)||(this.aa[a]={});this.aa[a].hasOwnProperty(b)||(this.aa[a][b]={});this.aa[a][b].hasOwnProperty(c)&&this.aa[a][b][c]==e||(this.aa[a][b][c]=
e,this.u("varchanged_"+c,{}))}Vf(a){return this.N.hasOwnProperty(a)?this.N[a].Ic:null}zb(){return"object"}mc(a,b,c=!0){if(void 0===b)return!1;let e=!1;this.N.hasOwnProperty(a)&&(0==this.N[a].Ib?(this.rh(this.zb(),a,b),e=!0):1==this.N[a].Ib&&this.F&&(this.Pe(this.zb(),this.F.id,a,b),e=!0));if(this.ka.hasOwnProperty(a)){var m=this.ka[a];if(m.value!=b){E.uh(m,b);if(m.$c&&c){if(""!=this.qb){m={};c=Object.keys(this.ka);for(q of c)this.ka[q].$c&&(m[q]=encodeURIComponent(this.ka[q].value.toString()));var q=
this.qb+"="+JSON.stringify(m);q=E.Hd(q,this.bf,this.cf)}else q="ggvar_"+a+"="+encodeURIComponent(b.toString()),q=E.Hd(q,m.Qd,m.Rd?m.Rd:"");document.cookie=q}e||this.u("varchanged_"+a,{value:b})}return!0}return!1}Wb(a,b){return 0==b?this.Ta(a):a}zg(a,b=""){if(this.N.hasOwnProperty(a)){if(0==this.N[a].Ib)return this.vg(this.zb(),a);if(1==this.N[a].Ib){if(""!=b||this.F&&this.F!=this.ga)return this.de(this.zb(),""!=b?b:this.F.id,a);switch(this.N[a].za){case 0:return"";case 1:return 0;case 2:return!1}}}if(this.ka.hasOwnProperty(a))return this.Wb(this.ka[a].value,
this.ka[a].type)}static Gc(a){let b="";let c,e,m,q=0;a=a.replace(/[^A-Za-z0-9+\/=]/g,"");do{var n="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(q++));var t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(q++));e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(q++));m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(q++));n=n<<2|t>>4;t=(t&15)<<4|e>>2;
c=(e&3)<<6|m;b+=String.fromCharCode(n);64!=e&&(b+=String.fromCharCode(t));64!=m&&(b+=String.fromCharCode(c))}while(q<a.length);return b}static Fh(a){const b=[1,1,1,1,2,2,3,0],c=a.length;let e="";for(let m=0;m<c;){let q=a.charCodeAt(m++);if(q&128){let n=b[q>>3&7];if(!(q&64&&n)||m+n>c)return null;for(q&=63>>n;0<n;--n){let t=a.charCodeAt(m++);if(128!=(t&192))return null;q=q<<6|t&63}}e+=String.fromCharCode(q)}return e}static Kf(a){return E.Fh(E.Gc(a))}constructor(){this.Dd="aHR0cHM6Ly9nZ25vbWUuY29t";
this.Ed="Q3JlYXRlZCBieSBHbm9tZXM=";this.Ae="TGljZW5zZTogYW5kcmVhcyBmdWhyZXI=";this.pf=!0;this.U={width:10,height:10};this.crossOrigin="anonymous";this.Gd=1;this.T={};this.Hb=this.wb="";this.Le=[];this.xe=!1;this.ac=0;this.control=this.S=this.Z=this.B=this.X=null;this.Na=[];this.D=this.qa=!1;this.C=null;this.Yb=!1;this.ic=0;this.W=null;this.ta={};this.tb={};this.aa={};this.N={};this.H={mode:1,ye:-1,P:0,R:0,ua:.05,La:255,Va:1,ma:255,Ua:.3,Xb:!0,pd:{enabled:!0,width:180,height:20,qd:0,df:1,background:!0,ma:16777215,Ua:1,La:0,
Va:1,vc:3,wc:1,uc:!0},ba:[],ia:[],sa:[],oc:[]};this.Pa=null;this.K=[];this.ga={};this.Dg=this.Vg=!1;this.Dh=-1;this.V=null;this.xb={};this.ka={};this.cf=this.qb="";this.bf=-1;this.margin={left:new H,top:new H,right:new H,bottom:new H,transition:{}};this.fc=[];this.M={x:0,y:0};this.Eg=!1;this.Ka="";this.Mf="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYBgeACDAAADIAAE3iTbkAAAAAElFTkSuQmCC";this.na="";this.Uc=this.Yc=
this.te=this.Tc=this.Wc=this.Vc=this.Zc=this.$b=this.jb=this.re=this.qe=this.se=this.ue=this.Xc=this.we=!1;this.devicePixelRatio=1;this.Ce="<<LOG>>";this.vd=!1;this.ig=function(a){return a?this.ib()&&(a.clientX||a.clientY)?{x:a.clientX,y:a.clientY}:a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:a.clientX||a.clientY?{x:a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,y:a.clientY+document.body.scrollTop+document.documentElement.scrollTop}:a.touches&&a.touches[0]?{x:a.touches[0].pageX,
y:a.touches[0].pageY}:{x:0,y:0}:{x:0,y:0}};this.jg=function(a){a=this.ig(a);let b=this.Ga();return{x:a.x-b.x,y:a.y-b.y}};this.yh=function(a,b,c){let e=this;var m="<<L>>"+String(e.na);m=m.toUpperCase();"U"!=m.charAt(2)&&(e.m.Zb=!1);if(e.wa)e.B.removeChild(e.wa),e.wa=null;else{e.wa=document.createElement("div");var q=e.wa;m="left: "+a+"px;top:\t "+(b+"px;z-index: 32000;");m+="position:relative;";m+="display: table;";m+="color: black;";m+="background-color: white;";m+="border: 1px solid lightgray;";
m+="box-shadow: 1px 1px 3px #333;";m+="font-family: Verdana, Arial, Helvetica, sans-serif;";m+="font-size: 9pt;";m+="opacity : 0.95;";q.setAttribute("style",m);q.setAttribute("class","gg_contextmenu");m=document.createElement("style");a=document.createTextNode(".gg_context_row:hover { background-color: #3399FF }");m.type="text/css";m.styleSheet?m.styleSheet.cssText=a.nodeValue:m.appendChild(a);q.appendChild(m);for(a=0;a<e.fc.length;a++){b=e.fc[a];if(""==b.text)continue;let n=document.createElement("div");
m="text-align: left;";m+="margin: 0;";m+="padding: 5px 20px;";m+="vertical-align: left;";n.setAttribute("style",m);n.setAttribute("class","gg_context_row");""!=b.url?(m=document.createElement("a"),m.href=b.url,m.target="_blank",m.innerHTML=this.Ta(b.text),m.setAttribute("style","color: black; text-decoration: none;"),n.appendChild(m)):(m=document.createElement("span"),m.innerHTML=this.Ta(b.text),m.setAttribute("style","color: black; text-decoration: none;"),n.appendChild(m));q.appendChild(n)}0<e.fc.length&&
(0<c.length||!e.m.Zb)&&q.appendChild(document.createElement("hr"));for(m=0;m<c.length;m++)a=c[m],a.hasOwnProperty("hr")?q.appendChild(document.createElement("hr")):(b=document.createElement("div"),b.setAttribute("class","gg_context_row"),a.hasOwnProperty("style")&&b.setAttribute("style",a.style),a.hasOwnProperty("onclick")&&(b.onclick=a.onclick),b.innerHTML=a.innerHTML,q.appendChild(b));e.m.Zb||(c=document.createElement("div"),m="text-align: left;margin: 0;padding: 5px 20px;",m+="vertical-align: left;",
c.setAttribute("style",m),c.setAttribute("class","gg_context_row"),m=document.createElement("a"),m.href=E.Gc(e.Dd),m.target="_blank",m.innerHTML=E.Gc(e.Ed),7<this.Ce.length&&(m.innerHTML+="<br/>"+E.Kf(e.Ce).replace(/./gm,function(n){return"&#"+n.charCodeAt(0)+";"})),m.setAttribute("style","color: black; text-decoration: none;"),c.appendChild(m),q.appendChild(c));e.B.insertBefore(e.wa,e.B.firstChild);q.onclick=function(){e.wa&&(e.B.removeChild(e.wa),e.wa=null)};q.oncontextmenu=q.onclick}};this.Jb=
"";this.Td();this.checkLoaded=this.Na;this.isLoaded=!1}Td(){this.devicePixelRatio=window.devicePixelRatio||1;this.we=!!navigator.userAgent.match(/(Windows|Win)/g);this.Xc=!!navigator.userAgent.match(/(Mac|Macintosh|Mac_powerpc)/g)&&!navigator.userAgent.match(/(like Mac)/g);this.ue=!!navigator.userAgent.match(/(Linux|Ubuntu)/g);this.se=!!navigator.userAgent.match(/(MSIE)/g);this.qe=!!navigator.userAgent.match(/(Edge|EdgA|Edg)/g);this.re=!!navigator.userAgent.match(/(Firefox)/g);if(this.jb=!!navigator.userAgent.match(/(Safari)/g)){var a=
navigator.userAgent.indexOf("Safari");this.Qa=navigator.userAgent.substring(a+7);a=navigator.userAgent.indexOf("Version");-1!=a&&(this.Qa=navigator.userAgent.substring(a+8));this.Qa=this.Qa.substring(0,this.Qa.indexOf(" "));this.Qa=this.Qa.substring(0,this.Qa.indexOf("."))}if(this.$b=!!navigator.userAgent.match(/(Chrome|CriOS)/g))this.jb=!1;navigator.userAgent.match(/(SamsungBrowser)/g);if(this.Zc=!!navigator.userAgent.match(/(OculusBrowser)/g))this.jb=this.$b=!1;this.Vc=!!navigator.userAgent.match(/(iPad|iPhone|iPod)/g);
this.Wc=!!navigator.userAgent.match(/(iPad)/g)||this.Xc&&2<navigator.maxTouchPoints;navigator.userAgent.match(/(iPhone|iPod)/g);this.Tc=!!navigator.userAgent.match(/(android)/i);this.te=!!navigator.userAgent.match(/(IEMobile)/i);this.Yc=this.Vc||this.Tc||this.te||this.Wc;/iP(hone|od|ad)/.test(navigator.platform)&&navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);this.Uc=!window.requestAnimationFrame;try{window.AudioContext=window.AudioContext||window.webkitAudioContext,new AudioContext}catch(b){}this.na=
"";a=["Webkit","Moz","O","ms","Ms"];for(let b=0;b<a.length;b++)"undefined"!==typeof document.documentElement.style[a[b]+"Transform"]&&(this.na="-"+a[b].toLowerCase()+"-")}Be(a){let b=document.getElementById("gg_debug");b&&(b.innerHTML=a+"<br />");window.console&&window.console.log(a)}setCrossOrigin(a){this.crossOrigin=a}ih(){}pg(){return this.ic}gh(a){this.Ka=a}Zd(){return this.Ka}bg(){return this.Yc}be(){return this.Eg}kh(a){this.Yc=!!a}$f(){return this.isLoaded}ag(){return!this.isLoaded}nc(a,b){try{this.qa&&
(a=window.innerWidth,b=window.innerHeight);let m=a-this.margin.left.v-this.margin.right.v,q=b-this.margin.top.v-this.margin.bottom.v;if(!(10>m||10>q)){this.X.style.width=m+"px";this.X.style.height=q+"px";this.X.style.left=this.margin.left.v+"px";this.X.style.top=this.margin.top.v+"px";this.Z&&(this.Z.style.width=a+"px",this.Z.style.height=b+"px",this.S.style.width=a+"px",this.S.style.height=b+"px",this.S.width=a,this.S.height=b,this.S.style.left=this.margin.left.v+"px",this.S.style.top=this.margin.top.v+
"px",this.C&&this.C!=this.Z&&(this.C.style.width=a+"px",this.C.style.height=b+"px"));this.Yb&&(this.D=!0);var c=this.X.offsetWidth,e=this.X.offsetHeight;if(this.U.width!=c||this.U.height!=e)this.U.width=c,this.U.height=e;this.C&&this.C.ggUpdateSize&&this.C.ggUpdateSize(a,b);this.u("sizechanged",{w:a,h:b});this.u("playerstatechanged",{})}}catch(m){}}sb(){this.vd=!0}wd(){this.Vh();this.nc(this.V.offsetWidth,this.V.offsetHeight)}Vh(){this.margin.left.rb(this.V.offsetWidth);this.margin.top.rb(this.V.offsetHeight);
this.margin.right.rb(this.V.offsetWidth);this.margin.bottom.rb(this.V.offsetHeight)}le(a=!1){let b={width:0,height:0};b.width=this.U.width+(a?this.margin.left.v+this.margin.right.v:0);b.height=this.U.height+(a?this.margin.top.v+this.margin.bottom.v:0);return b}Ga(){let a={x:0,y:0},b=this.X.getBoundingClientRect();a.x=b.left;a.y=b.top;this.jb&&14>Number(this.Qa)&&(a.x=b.left+window.scrollX,a.y=b.top+window.scrollY);return a}qh(a){this.W=a}lh(a,b,c,e){let m=!0;"object"===typeof a?(a.hasOwnProperty("left")&&
this.margin.left.kc(a.left,a.transition,this.V.offsetWidth),a.hasOwnProperty("top")&&this.margin.top.kc(a.top,a.transition,this.V.offsetHeight),a.hasOwnProperty("right")&&this.margin.right.kc(a.right,a.transition,this.V.offsetWidth),a.hasOwnProperty("bottom")&&this.margin.bottom.kc(a.bottom,a.transition,this.V.offsetHeight),a.hasOwnProperty("transition")&&a.transition.hasOwnProperty("duration")&&0<a.transition.duration&&(m=!1,this.margin.transition.duration=a.transition.duration,a.transition.hasOwnProperty("timingfunction")?
this.margin.transition.timingfunction=a.transition.timingfunction:this.margin.transition.timingfunction="ease")):(this.margin.left.value=a,this.margin.top.value=b,this.margin.right.value=c,this.margin.bottom.value=e);this.W=this.skinObj;m?this.sb():(b=0,a.transition.hasOwnProperty("delay")&&(b=a.transition.delay),setTimeout(()=>{this.Qh(this)},b))}Qh(a){a.margin.transition.starttime=(new Date).getTime();a.margin.transition.interval&&clearInterval(a.margin.transition.interval);a.margin.transition.interval=
setInterval(()=>{a.Rh(a)},20)}Rh(a){var b=((new Date).getTime()-a.margin.transition.starttime)/a.margin.transition.duration;b=Math.max(b,0);b=Math.min(b,1);switch(a.margin.transition.timingfunction){case "ease-in":b=1-Math.cos(b*Math.PI/2);break;case "ease-out":b=Math.sin(b*Math.PI/2);break;case "ease":b=-(Math.cos(Math.PI*b)-1)/2;break;case "ease-in-out":b=.5>b?4*b*b*b:1-Math.pow(-2*b+2,3)/2;break;case "step-end":b=1==b?1:0}b=Math.round(100*b)/100;a.margin.left.Tb(b,a.V.offsetWidth);a.margin.top.Tb(b,
a.V.offsetHeight);a.margin.right.Tb(b,a.V.offsetWidth);a.margin.bottom.Tb(b,a.V.offsetHeight);a.nc(a.V.offsetWidth,a.V.offsetHeight);1<=b&&(clearInterval(a.margin.transition.interval),a.margin.transition.interval=0)}Od(a){0==a&&(this.m.Bb=!1);1==a&&(this.m.Bb=!0);2==a&&(this.m.Bb=!this.m.Bb);this.u("viewmodechanged",{});this.u("playerstatechanged",{})}je(){return 1==this.m.Bb?1:0}Nd(a,b){this.H.mode=1==b&&0<this.H.mode?0:Math.round(a);this.update();this.u("polymodechanged",{})}mf(a){let b=this.Ga();
this.ib()?(this.M.x=a.clientX-this.margin.left.v,this.M.y=a.clientY-this.margin.top.v):(this.M.x=a.clientX-b.x,this.M.y=a.clientY-b.y)}yb(a){let b=[];a="*"==a?"^.*$":"#"==a.substring(0,1)?a.substring(1):"^"+a+"$";a=new RegExp(a,"");for(var c=0;c<this.K.length;c++)"poly"==this.K[c].type&&a.test(this.K[c].id)&&b.push(this.K[c]);return b}Xe(a){a=this.yb(a);for(var b=0;b<a.length;b++){let c=this.H.ba.indexOf(a[b].id);-1==c?(this.H.ba.push(a[b].id),this.H.ia.push(0),this.H.sa.push(1)):this.H.sa[c]=1}this.update()}me(a){a=
this.yb(a);for(var b=0;b<a.length;b++){let c=this.H.ba.indexOf(a[b].id);-1!=c&&(this.H.sa[c]=0,this.H.oc.push(a[b].id),this.update())}}Lh(a){a=this.yb(a);for(var b=0;b<a.length;b++){let c=this.H.ba.indexOf(a[b].id);-1==c||-1!=c&&0==this.H.sa[c]?this.Xe(a[b].id):this.me(a[b].id);this.update()}}Ef(a,b,c,e,m){let q;q=""==a?this.K:this.yb(a);for(let n=0;n<q.length;n++){let t=q[n];"poly"==t.type&&(t.ma=b,t.Ua=c,t.La=e,t.Va=m)}""==a&&(this.H.ma=b,this.H.Ua=c,this.H.La=e,this.H.Va=m);this.update()}oh(a,
b){let c;c=""==a?this.K:this.yb(a);for(let e=0;e<c.length;e++){let m=c[e];"poly"==m.type&&(m.Xb=b)}""==a&&(this.H.Xb=b);this.update()}sg(){return this.H.mode}Bc(){this.u("viewstatechanged",{})}ke(){return 0}Kb(a,b,c){var e=(new RegExp("%0*"+b,"i")).exec(a.toString());if(e){e=e.toString();let m=c.toString();e.charAt(e.length-1)!=b&&(m=(1+c).toString());if(!isNaN(parseFloat(c)))for(;m.length<e.length-1;)m="0"+m;a=a.replace(e,m)}return a}td(){this.u("hotspotsupdated",{})}Uf(){let a=[];for(let b=0;b<
this.K.length;b++){let c=this.K[b];"point"==c.type&&c.O&&c.O.__div&&a.push(c.O.__div)}return a}Ab(a,b){a=Number(a);isNaN(b)&&(b=0);0>b&&(b=0);1<b&&(b=1);return"rgba("+(a>>16&255)+","+(a>>8&255)+","+(a&255)+","+b+")"}aspect(){return this.U.width/this.U.height}fb(){}update(){this.D=!0}cg(){return!1}ph(a){this.Jb=a}getQueryParameter(){return this.Jb}Kc(a){if(a){if("{"==a.charAt(0)||"/"==a.charAt(0)||0<a.indexOf(":"))return a;""!=this.Jb&&(a=-1==a.indexOf("?")?a+("?"+this.Jb):a+("&"+this.Jb));return this.Ka+
a}return this.Ka}Vb(){return 0}mg(){return 0}ld(){}zc(){}ie(){return 0}yg(){return 0}md(){}Ac(){}hb(){return 0}Nb(){return!1}xc(){return!1}Oe(){}setLocked(a){this.Se(a);this.Te(a);this.Re(a)}Se(a){this.m.ha=!!a}Re(a){this.m.Za=!!a}fg(){return this.m.Za}Te(a){this.m.cd=!!a}Bg(){return this.m.Xh}wh(a){this.m.Xh=a}lg(){return this.Tc?5:this.Wc?6:this.Vc?4:this.we?1:this.Xc?2:this.ue?3:0}Sf(){return this.se?5:this.qe?4:this.re?2:this.jb?3:this.$b?1:this.Zc?6:0}Tf(){return window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?
1:0}moveTo(){this.I()}Ng(){this.I()}Ge(){}Mg(){}wf(){}Uh(a,b,c){for(let e=0;e<this.K.length;e++){let m=this.K[e];m.id==a&&(m.pan=b,m.ja=c,m.di())}this.D=!0}$g(a){let b=-1,c;for(let e=0;e<this.K.length;e++)c=this.K[e],c.id==a&&(b=e);-1<b&&(c=this.K.splice(b,1).pop(),c.O&&c.O.__div&&this.Z.removeChild(c.O.__div))}rg(){let a=[];for(let b=0;b<this.K.length;b++){let c=this.K[b];"point"==c.type&&a.push(String(c.id))}return a}ce(){}sc(a,b,c){const e=this.H.pd,m=this.Pa;e.enabled&&(this.F!=this.ga&&0<=a&&
0<=b&&""!=this.F.title?(m.innerHTML=this.Ta(this.F.title),m.style.color=this.Ab(e.qd,e.df),m.style.backgroundColor=e.background?this.Ab(e.ma,e.Ua):"transparent",m.style.border="solid "+this.Ab(e.La,e.Va)+" "+e.wc+"px",m.style.borderRadius=e.vc+"px",m.style.textAlign="center",0<e.width?(m.style.left=a-e.width/2+this.margin.left.v+"px",m.style.width=e.width+"px"):(m.style.width="auto",m.style.left=a-m.offsetWidth/2+this.margin.left.v+"px"),m.style.height=0<e.height?e.height+"px":"auto",m.style.top=
b+(c?-60:25)+this.margin.top.v+"px",m.style.visibility="inherit",m.style.whiteSpace=e.uc?"pre-wrap":"nowrap",m.style.overflow="hidden"):(m.style.visibility="hidden",m.innerHTML=""))}jf(a){this.W&&this.W.hotspotProxyClick&&this.W.hotspotProxyClick(a.id,a.url);this.u("hsproxyclick",{id:this.F.id,url:this.F.url});""!=a.url&&this.ed(a.url,a.target);this.sc(-1,-1,!1)}kf(a){this.W&&this.W.hotspotProxyDoubleClick&&this.W.hotspotProxyDoubleClick(a.id,a.url);this.u("hsproxydblclick",{id:this.F.id,url:this.F.url})}I(){this.bc=
(new Date).getTime()}eg(){return this.bc}ib(){return document.webkitIsFullScreen||document.mozFullScreen||document.msFullscreenElement&&null!=document.msFullscreenElement||document.fullScreen}Hg(a){a=Number(a).toString(16);return a="#000000".substring(0,7-a.length)+a}Ig(){}fe(){return null}hg(){return null}isPlaying(){return!1}jc(){}Je(){}Ke(){}fd(){}vf(){}od(){}Ah(){return 0}Ch(){}Bh(){}setVolume(){}Gf(){}Qg(){}Sh(){}Kh(){}qg(){return this.Vg}Wf(){return this.Dg}ug(){return this.Dh}Eh(){}mh(){}ah(){}Yf(){return!0}cb(a){let b=
this.qa!==a;this.qa!==a&&(this.qa=a,this.update(100));if(this.qa){if(this.pf)try{this.B.webkitRequestFullScreen?this.B.webkitRequestFullScreen():this.B.mozRequestFullScreen?this.B.mozRequestFullScreen():this.B.msRequestFullscreen?this.B.msRequestFullscreen():this.B.requestFullScreen?this.B.requestFullScreen():this.B.requestFullscreen&&this.B.requestFullscreen()}catch(c){}this.B.style.position="absolute";a=this.Ga();this.B.style.left=window.pageXOffset-a.x+this.margin.left.v+"px";this.B.style.top=
window.pageYOffset-a.y+this.margin.top.v+"px";document.body.style.overflow="hidden";b&&(this.C&&this.C.ggEnterFullscreen&&this.C.ggEnterFullscreen(),this.u("fullscreenenter",{}),this.u("playerstatechanged",{}))}else{if(this.pf)try{document.webkitIsFullScreen?document.webkitCancelFullScreen():document.mozFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.fullScreen&&(document.cancelFullScreen?document.cancelFullScreen():document.exitFullscreen&&
document.exitFullscreen())}catch(c){}this.B.style.position="relative";this.B.style.left="0px";this.B.style.top="0px";document.body.style.overflow="";b&&(this.C&&this.C.ggExitFullscreen&&this.C.ggExitFullscreen(),this.u("fullscreenexit",{}),this.u("playerstatechanged",{}))}this.sb()}qc(){this.cb(!this.qa)}Nf(){this.cb(!0)}exitFullscreen(){this.cb(!1)}ee(){return this.qa}hc(){this.qa&&(this.ib()||this.exitFullscreen(),this.ib()&&(this.B.style.left="0px",this.B.style.top="0px"))}Ze(){}af(){}hf(){}Ug(){this.I()}dh(){}fh(){}hh(){}Dc(){}he(){let a=
1,b=-1!=navigator.userAgent.indexOf("Mac");window.devicePixelRatio&&b&&(a=window.devicePixelRatio);return{w:screen.width*a,h:screen.height*a}}gg(){let a=this.he();return a.w>a.h?a.w:a.h}Of(a){try{let b=a.getAttributeNode("variablename"),c=b.nodeValue.toString();b=a.getAttributeNode("variabletype");let e=Number(b.nodeValue);b=a.getAttributeNode("propertytype");let m=Number(b.nodeValue);b=a.getAttributeNode("defaultvalue");let q;b&&(q=b.nodeValue.toString());this.N[c]={za:e,Ib:m,Ic:q}}catch(b){console.error(b)}}Pf(a){let b=
{},c=a.firstChild;for(;c;){if("custompropertyvalue"==c.nodeName){a=c.getAttributeNode("value");let e=a.nodeValue.toString();a=c.getAttributeNode("variablename");b[a.nodeValue.toString()]=e}c=c.nextSibling}return b}Vd(a){let b,c="";(b=a.getAttributeNode("id"))&&(c=b.nodeValue.toString());if(!this.aa.hasOwnProperty("object")||!this.aa.object.hasOwnProperty(c)){var e={};for(a=a.firstChild;a;){if("custompropertyvalue"==a.nodeName){b=a.getAttributeNode("variablename");let m=b.nodeValue;b=a.getAttributeNode("value");
e[m]=b.nodeValue}a=a.nextSibling}this.aa.object||(this.aa.object={});this.aa.object[c]=e}}gd(a,b){a=(new DOMParser).parseFromString(a,"text/xml");this.hd(a,b)}Xg(a,b,c){try{let e;e=new XMLHttpRequest;e.open("GET",a,!1);e.send(null);if(e.responseXML){let m=a.lastIndexOf("/");0<=m&&(this.Ka=a.slice(0,m+1));2<=arguments.length&&null!=b&&(this.Ka=b);this.gd(e.responseText,c)}else alert("Error loading panorama XML")}catch(e){alert("Error:"+e)}}Yg(a,b,c,e){let m;m=new XMLHttpRequest;let q=this;m.onload=
function(n){if(4<=m.readyState)if(m.responseXML){let t=a.lastIndexOf("/");0<=t&&(q.Ka=a.slice(0,t+1));3<=arguments.length&&null!=c&&(q.Ka=c);q.gd(m.responseText,e);b&&b()}else alert("Error loading panorama XML");else console.error("Wrong state loading XML:"+m.statusText)};m.onerror=function(){console.error("Error loading XML:"+m.statusText)};m.open("GET",a,!0);m.send(null)}hd(){}ed(a,b){0<a.length&&".xml"!=a.slice(-4)&&".swf"!=a.slice(-4)&&"{"!=a.charAt(0)&&window.open(this.Kc(a),b)}Ud(){}ge(){return{}}Ue(){return!0}}
class L extends E{Pc(a){return-99991===a?this.Ae:"4.0/20804"}ne(){return this.j.Ea%this.j.G+(this.j.Fa%this.j.G+this.j.va%this.j.Ha*this.j.L)*this.j.G}constructor(a,b){super(a,b);this.pan={o:0,Wa:0,min:0,max:360,d:0,Da:0};this.ja={o:0,Wa:0,min:-90,max:0,d:0,Da:0};this.fov={o:90,Wa:90,min:1,max:170,prev:0,d:0,mode:0};this.zoom={o:1,Wa:1,min:1,max:1,ec:0,A:-1,d:0,cx:0,cy:0,cc:0,dc:0,viewport:1,Ne:1,$e:0,Sd:0,prev:0};this.ya={start:{x:0,y:0},A:{x:0,y:0},ra:{x:0,y:0},o:{x:0,y:0},J:{x:0,y:0}};
this.ca={Lc:0,$:!1,start:{x:0,y:0},A:{x:0,y:0},ra:{x:0,y:0},o:{x:0,y:0},J:{x:0,y:0},startTime:0,pb:null};this.kb=0;this.ve=!1;this.Db={enabled:!0,A:{x:0,y:0},J:{x:0,y:0},fov:{active:!1,Lf:0}};this.Ya=!1;this.Fg={enabled:!1,If:0,gi:0,pd:{enabled:!0,width:180,height:20,qd:0,background:!0,ma:16777215,La:0,vc:1,wc:1,uc:!0},area:[]};this.F=this.ga={pan:0,ja:0,title:"",url:"",target:"",id:"",zh:"",w:100,h:20,uc:!1,O:null,R:0};this.xd={};this.vb=this.Fc=this.oa=this.Ma=this.fa=this.Oa=this.xa=this.Y=null;
this.jh=!0;this.oe=!1;this.Ca={enabled:!1,delay:5,active:!1,speed:.4,pingpong:!1,ad:Date.now()};this.ub={active:!1,speed:.1,x:0,y:0,fov:100,cx:0,cy:0,Ia:0};this.Xa=!1;this.ta={title:"",description:"",Yh:"",ci:"",$h:"",source:"",fi:"",Zh:""};this.Sg={target:0,current:0,ua:.01,delay:2,Jc:0,Sb:!1,Af:!1};this.m={mode:3,Za:!1,ha:!1,cd:!1,Bb:!0,Id:!0,Qb:!0,ab:!1,pe:!1,Ye:1,Hc:!0,Aa:!1,Ba:!1,Lb:!1,Mb:!1,ea:!1,sensitivity:10,Pd:!1,Zb:!1};this.j={x:0,y:0,dx:0,dy:0,width:100,height:100,state:0,Ea:-1,Fa:-1,
va:-1,G:1,L:1,Ha:1,nb:0,ob:0,pc:0,path:"images/",ext:"jpg",Rc:!1,levels:[],da:512,hi:1,bd:1,ze:"",preload:!1};this.nd=[];this.config={background:!0,ma:0};this.Qc=!1;this.Wd=!0;this.Ja=0;this.Ih=5;this.ff=function(){this.Ja&&this.Ja--;0==this.Ja&&this.C&&this.C.ggLoadedLevels&&this.C.ggLoadedLevels()};this.Cb=!1;this.We=function(c,e){this.j.x=c;this.j.y=e;this.fb();this.D=!0};this.yd=function(c,e){const m=this.hb();this.m.ab?(this.zoom.cx+=c/(this.zoom.o*this.zoom.viewport),this.zoom.cy+=e/(this.zoom.o*
this.zoom.viewport)):(this.zd(-c/20),this.Ad(-e/20));this.pan.Da+=c*m/this.U.height;this.ja.Da+=e*m/this.U.height;this.pan.o=this.pan.Da;this.ja.o=this.ja.Da;this.fb()};this.He=function(c){window.MSGesture&&(this.lb||(this.lb=new window.MSGesture,this.lb.target=this.control),this.lb.addPointer(c.pointerId))};this.Eb=1;this.Bd=function(c){this.m.Lb&&(c=-c);this.j.x+=c;this.fb()};this.Cd=function(c){this.m.Mb&&(c=-c);this.j.y+=c;this.fb()};this.rd=function(c,e,m,q,n,t){const r=this.j,f=r.levels.length-
1-q;let w=r.ze;w=this.Kb(w,"c",c%r.G+(e%r.L+m%r.Ha*r.L)*r.G);w=this.Kb(w,"r",q);w=this.Kb(w,"l",f);w=this.Kb(w,"x",n);w=this.Kb(w,"y",t);return this.Kc(w)};this.Wg=function(){const c=this,e=c.j;var m,q,n,t;if(0<e.levels.length)for(t=0;t<e.levels.length;t++){var r=e.levels[t];if(r.cache)for(n=0;n<e.Ha;n++)for(q=0;q<e.L;q++)for(m=0;m<e.G;m++){var f=[],w,x;for(x=0;x<r.Ob;x++)for(w=0;w<r.Ra;w++){var v=w+x*r.Ra;var y={};y.j=new Image;y.j.setAttribute("src",c.rd(m,q,n,t,w,x));y.j.onload=function(){c.D=
!0;c.Xa=!0};f[v]=y;c.Na.push(y.j)}r.sd[m+e.G*(q+n*e.L)]=f}}else if(e.preload)for(t=new Image,t.src=c.Sc(e.nb,e.ob,e.pc),n=0;n<e.Ha;n++)for(q=0;q<e.L;q++)for(m=0;m<e.G;m++)t=new Image,t.src=c.Sc(m,q,n),c.Na.push(t)};this.jd=0;this.Ub=!0;this.Dd="aHR0cHM6Ly9vYmplY3QydnIuY29tLw==";this.Ed="Q3JlYXRlZCB3aXRoIE9iamVjdDJWUg==";b&&(b.hasOwnProperty("three")&&(this.THREE=b.three),b.hasOwnProperty("threeLoader")&&(this.uf=b.threeLoader));this.Be("Object2VR player "+this.Pc()+" - Prefix:  "+this.na);this.addListener("languagechanged",
()=>{});this.userdata=this.ta;this.emptyHotspot=this.ga;this.mouse=this.M;this.bb(this.ga);this.Dc(a);this.Ya&&(this.Ma.style.display="none",this.fa.style.display="none",this.Gh());this.zf();this.I()}nc(a,b){var c=this.U;const e=this.margin,m=this.X,q=this.Z;let n=this.fa,t=this.Ma;this.ee()&&("number"==typeof window.innerWidth?(a=window.innerWidth,b=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(a=document.documentElement.clientWidth,
b=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||document.body.clientHeight)&&(a=document.body.clientWidth,b=document.body.clientHeight));let r=a-e.left.v-e.right.v,f=b-e.top.v-e.bottom.v;c.width=r;c.height=f;m.style.width=r+"px";m.style.height=f+"px";m.style.left=e.left.v+"px";m.style.top=e.top.v+"px";this.lf();q.style.width=a+"px";q.style.height=b+"px";this.S.style.width=a+"px";this.S.style.height=b+"px";this.S.width=a;this.S.height=b;this.S.style.left=e.left.v+
"px";this.S.style.top=e.top.v+"px";n.style.width=a+"px";n.style.height=b+"px";t.style.width=a+"px";t.style.height=b+"px";if(this.Wd){if(!this.oa)try{this.Fc=t.getContext("2d"),this.vb=this.oa=n.getContext("2d")}catch(w){}try{this.oa?(m.removeChild(this.xa),m.removeChild(this.Y)):(m.removeChild(n),m.removeChild(t))}catch(w){}this.Wd=!1}this.oa&&(c=window.devicePixelRatio||1,n.width!=Math.round(a*c)||n.height!=Math.round(b*c))&&(n.width=Math.round(a*c),n.height=Math.round(b*c),t.width=Math.round(a*
c),t.height=Math.round(b*c),this.oa.scale(c,c),this.Fc.scale(c,c),this.Xa=this.D=!0);this.D=!0;this.C&&this.C.ggUpdateSize&&this.C.ggUpdateSize(a,b);this.u("sizechanged",{w:a,h:b});this.u("playerstatechanged",{})}Jh(){this.Xa=this.D=!0;this.Ja&&this.Ja--;0==this.Ja&&this.C&&this.C.ggLoadedLevels&&this.C.ggLoadedLevels()}lf(){const a=this,b=a.zoom,c=a.U,e=a.j;var m=a.oa;const q=a.vb;var n=a.Y;var t=a.xa;switch(b.Ne){case 1:b.viewport=Math.min(c.width/e.width,c.height/e.height);break;case 2:b.viewport=
Math.max(c.width/e.width,c.height/e.height);break;case 3:b.viewport=c.width/e.width;break;case 4:b.viewport=c.height/e.height;break;default:b.viewport=1}var r=b.viewport*b.o*(b.cx-e.width/2)+c.width/2;var f=b.viewport*b.o*(b.cy-e.height/2)+c.height/2;let w,x;r=Math.round(r);f=Math.round(f);w=Math.round(e.width*b.viewport*b.o);x=Math.round(e.height*b.viewport*b.o);if(m){if(a.Cb=!1,0<=e.Ea&&0<=e.Fa){(w<c.width||x<c.height)&&b.A>b.o&&(q.clear?q.clear():q.clearRect(0,0,a.fa.width,a.fa.height));if(0<e.levels.length){let C=
0,z,D,F;for(;e.levels.length>=C+2&&e.levels[C+1].width>w;)C++;let G=C;for(var v=!1;!v;){v=!0;z=e.levels[G];t=-r/w*(z.width/e.da);var y=-f/x*(z.height/e.da);n=(-r+c.width)/w*(z.width/e.da);m=(-f+c.height)/x*(z.height/e.da);t=Math.min(Math.max(0,Math.floor(t)),z.Ra-1);y=Math.min(Math.max(0,Math.floor(y)),z.Ob-1);n=Math.min(Math.max(0,Math.floor(n)),z.Ra-1);m=Math.min(Math.max(0,Math.floor(m)),z.Ob-1);for(F=y;F<=m;F++)for(D=t;D<=n;D++){var A=D+F*z.Ra;(y=z.Sa[A])&&y.j?y.j.complete||(v=!1):v=!1}v||(G+
1<e.levels.length?G++:v=!0)}e.Rc&&G+1<e.levels.length&&G++;for(v=G;G>=C;){z=e.levels[G];t=-r/w*(z.width/e.da);y=-f/x*(z.height/e.da);n=(-r+c.width)/w*(z.width/e.da);m=(-f+c.height)/x*(z.height/e.da);t=Math.min(Math.max(0,Math.floor(t)),z.Ra-1);y=Math.min(Math.max(0,Math.floor(y)),z.Ob-1);n=Math.min(Math.max(0,Math.floor(n)),z.Ra-1);m=Math.min(Math.max(0,Math.floor(m)),z.Ob-1);for(F=y;F<=m;F++)for(D=t;D<=n;D++)if(A=D+F*z.Ra,(y=z.Sa[A])||(y=z.Sa[A]={}),!y.j&&a.Ja<a.Ih&&(y.j=new Image,y.j.setAttribute("src",
a.rd(e.Ea,e.Fa,e.va,G,D,F)),y.j.onload=()=>{a.Jh()},y.j.onerror=()=>{a.ff()},y.j.onabort=()=>{a.ff()},0==a.Ja&&a.C&&a.C.ggReLoadedLevels&&a.C.ggReLoadedLevels(),a.Ja++),y.j&&y.j.complete){let I,J,K;A=r+(-e.bd+e.da*D)*w/z.width;I=f+(-e.bd+e.da*F)*x/z.height;J=y.j.width*w/z.width;K=y.j.height*x/z.height;e.Rc&&G==v&&q.clearRect(A,I,J,K);q.drawImage(y.j,A,I,J,K);a.Cb=!0}G--}b.A=b.o;b.cc=b.cx;b.dc=b.cy}else""!=a.Y.src&&a.Y.complete?(q.clear?q.clear():q.clearRect(0,0,a.fa.width,a.fa.height),q.drawImage(a.Y,
r,f,w,x),b.A=b.o,b.cc=b.cx,b.dc=b.cy,a.Cb=!0):a.D=!0;a.Cb&&a.td()}}else n.setAttribute("width",e.width+"px"),n.setAttribute("height",e.height+"px"),t.setAttribute("width",e.width+"px"),t.setAttribute("height",e.height+"px"),n.style.left=r+"px",n.style.top=f+"px",n.style.width=w+"px",n.style.height=x+"px",t.style.left=r+"px",t.style.top=f+"px",t.style.width=w+"px",t.style.height=x+"px",b.A=b.o,b.cc=b.cx,b.dc=b.cy}Th(){this.X.style.backgroundColor=this.config.background?this.Hg(this.config.ma):"transparent"}Vb(){const a=
this.pan;if(this.Ya)return a.o;let b;if(this.m.ea){if(1==this.j.L)return 0;b=this.j.y/(this.j.L-(this.m.Ba?0:1))}else{if(1==this.j.G)return 0;b=this.j.x/(this.j.G-(this.m.Aa?0:1))}return a.min+b*(a.max-a.min)}ng(){return this.Vb()+1}og(){return this.Vb()}Ie(a){const b=this.pan;a=(a-b.min)/(b.max-b.min);if(this.m.ea)return this.m.Ba&&(a-=Math.floor(a)),Number(a*(this.j.L-(this.m.Ba?0:1)));this.m.Aa&&(a-=Math.floor(a));return Number(a*(this.j.G-(this.m.Aa?0:1)))}gf(a){const b=this.ja;a=(a-b.min)/(b.max-
b.min);if(this.m.ea)return this.m.Aa&&(a-=Math.floor(a)),Number(a*(this.j.G-(this.m.Aa?0:1)));this.m.Ba&&(a-=Math.floor(a));return Number(a*(this.j.L-(this.m.Ba?0:1)))}ld(a){this.I();isNaN(a)||(this.Ya?this.pan.o=a:(a=this.Ie(a),this.m.ea?this.j.y=a:this.j.x=a));this.D=!0}zc(a){this.I();isNaN(a)||this.zd(a);this.D=!0}ie(){const a=this.ja;if(this.Ya)return a.o;let b;if(this.m.ea){if(1==this.j.G)return 0;b=this.j.x/(this.j.G-(this.m.Aa?0:1))}else{if(1==this.j.L)return 0;b=this.j.y/(this.j.L-(this.m.Ba?
0:1))}return a.min+b*(a.max-a.min)}md(a){this.I();this.Ya?this.ja.o=a:(a=this.gf(a),this.m.ea?this.j.x=a:this.j.y=a);this.D=!0}Ac(a){this.I();isNaN(a)||this.Ad(a);this.D=!0}Df(a,b){this.zc(a,b)}Ff(a,b){this.Ac(a,b)}hb(){return 100*this.zoom.o}Nb(a){this.I();this.eb(a/100);return!0}xc(a){return this.Nb(this.hb()-10*a)}yc(a){return this.Nb(this.hb()*Math.exp(-a/50))}Hf(a){this.I();this.eb(this.hb()*Math.exp(-a/50)/100)}Ag(){return this.zoom.o}eb(a){const b=this.zoom;isNaN(a)||(b.o=a<b.min?b.min:a>b.max?
b.max:a);this.D=!0}Xf(){return 1<this.zoom.max||0<this.zoom.ec}getX(){return this.j.Ea}getY(){return this.j.Fa}setX(a){isNaN(a)||(this.j.x=Number(a),this.D=!0)}setY(a){isNaN(a)||(this.j.y=Number(a),this.D=!0)}vh(a,b,c){this.I();this.setX(a);this.setY(b);this.eb(c)}setXY(a,b){this.I();this.setX(a);this.setY(b)}getState(){return this.j.va}wg(a){isNaN(a)&&(a=this.j.va);return this.nd.length>=this.j.Ha?this.nd[a]:""}Mc(){return this.j.G}Oc(){return this.j.L}xg(){return this.j.Ha}Kd(a){if(!a&&this.m.ea)return this.Ld(!0);
if(this.m.Aa)return!0;if(this.m.Lb){if(this.getX()<this.Mc()-1)return!0}else if(0<this.getX())return!0;return!1}Jd(a){if(!a&&this.m.ea)return this.Md(!0);if(this.m.Aa)return!0;if(this.m.Lb){if(0<this.getX())return!0}else if(this.getX()<this.Mc()-1)return!0;return!1}Md(a){if(!a&&this.m.ea)return this.Jd(!0);if(this.m.Ba)return!0;if(this.m.Mb){if(0<this.getY())return!0}else if(this.getY()<this.Oc()-1)return!0;return!1}Ld(a){if(!a&&this.m.ea)return this.Kd(!0);if(this.m.Ba)return!0;if(this.m.Mb){if(this.getY()<
this.Oc()-1)return!0}else if(0<this.getY())return!0;return!1}Bf(){return this.zoom.o<this.zoom.max}Cf(){return this.zoom.o>this.zoom.min}getCenter(){const a={};a.x=.5-this.zoom.cx/this.j.width;a.y=.5-this.zoom.cy/this.j.height;return a}nh(a,b,c){this.I();isNaN(a)||this.ld(a);isNaN(b)||this.md(b);!isNaN(c)&&0<c&&this.Nb(c);this.D=!0}Oe(){this.j.x=this.j.nb;this.j.y=this.j.ob;this.Bc(this.j.pc,0);this.zoom.o=this.zoom.Wa;this.D=!0}moveTo(a,b,c,e,m,q){const n=this.j;var t=this.zoom;let r=a.toString().split("/");
1<r.length&&(a=Number(r[0]),e=b,b=Number(r[1]),2<r.length&&(c=Number(r[2])));a=isNaN(a)?n.x:this.Ie(Number(a));b=isNaN(b)?n.y:this.gf(Number(b));c=!isNaN(c)&&0<c?Number(c/100):t.o;isNaN(e)&&(e=1);if(isNaN(m)||isNaN(q))q=m=0;this.m.ea&&(t=a,a=b,b=t);this.dd(a,b,c,e,m,q)}dd(a,b,c,e,m,q){const n=this.ub,t=this.j,r=this.zoom;this.I();this.ub.active=!0;let f=a.toString().split("/");1<f.length&&(a=Number(f[0]),e=b,b=Number(f[1]),2<f.length&&(c=Number(f[2])));n.x=isNaN(a)?t.x:Number(a);n.y=isNaN(b)?t.y:
Number(b);n.fov=!isNaN(c)&&0<c?Number(100*c):100*r.o;n.speed=!isNaN(e)&&0<e?Number(e):1;m&&!isNaN(m)&&q&&!isNaN(q)?(n.cx=Number(m),n.cy=Number(q),n.Ia=Math.ceil(20/n.speed),0>=n.Ia&&(n.Ia=1)):n.Ia=0}Ge(a){this.dd(this.j.nb,this.j.ob,this.zoom.Wa,a)}sf(a,b){this.ya.start.x=a;this.ya.start.y=b;this.ya.A.x=a;this.ya.A.y=b;this.Db.A.x=a;this.Db.A.y=b;this.pan.Da=this.pan.o;this.ja.Da=this.ja.o}rf(a,b){const c=this.ya;c.o.x=a;c.o.y=b;c.J.x=c.o.x-c.A.x;c.J.y=c.o.y-c.A.y;c.A.x=c.o.x;c.A.y=c.o.y}I(){this.Ca.active&&
(this.Ca.active=!1,this.u("autorotatechanged",{}),this.j.dx=0,this.j.dy=0);this.ub.active&&(this.ub.active=!1,this.j.dx=0,this.j.dy=0);this.bc=(new Date).getTime()}pa(a){return a==this.Y||a==this.xa||a==this.fa||a==this.Ma||a==this.control||a==this.S?!0:a&&void 0!==a.ggPermeable&&0==a.ggPermeable?!1:a&&a.ggType&&("container"==a.ggType||"cloner"==a.ggType||"timer"==a.ggType)?!0:!1}Ee(a){const b=a.touches;if(this.wa)this.wa.onclick();this.mf(a);this.m.ha||(a.which&&0!=a.which&&1!=a.which||!this.pa(a.target)||
(this.sf(a.pageX,a.pageY),b&&(this.ca.Lc=b[0].identifier),this.ca.$=!0,this.ca.startTime=(new Date).getTime(),this.I(),a.preventDefault?a.preventDefault():a.returnValue=!1),this.ya.J.x=0,this.ya.J.y=0)}bb(a){if("string"==typeof a)for(var b=0;b<this.K.length;b++)if(this.K[b].id==a){a=this.K[b];break}this.hotspot=this.F=a&&null!==a&&"object"==typeof a?a:this.ga;this.u("activehotspotchanged",{hotspot:this.F})}De(a){const b=this.margin;var c=this.m;const e=this.Fg,m=this.H;this.mf(a);if(1==this.Eb&&!c.ha&&
(this.ca.$&&(this.rf(a.pageX,a.pageY),this.I(),a.preventDefault?a.preventDefault():a.returnValue=!1),0==e.If&&this.F==this.ga||"poly"==this.F.type)){c=this.ga;this.pa(a.target)&&(c=this.Rb(this.M.x,this.M.y));if(this.F!=c)if(this.F!=this.ga&&(0<this.H.mode&&(this.F.R=0),this.W&&this.W.hotspotProxyOut&&this.W.hotspotProxyOut(this.F.id),this.u("hsproxyout",{id:this.F.id,url:this.F.url})),c){this.bb(c);this.W&&(this.W.hotspotProxyOver&&this.W.hotspotProxyOver(this.F.id),this.u("hsproxyover",{id:this.F.id,
url:this.F.url}));if("poly"!=this.F.type||0!=this.F.handcursor)this.Z.style.cursor="pointer";0<m.mode&&(m.R=1,this.F.R=1,this.D=!0)}else this.bb(this.ga),this.Z.style.cursor="auto",0<m.mode&&(m.R=0,this.D=!0);this.sc(this.M.x-b.left.v,this.M.y-b.top.v,!1)}}Lg(a){const b=this.ya,c=this.ca,e=this.m;if(!e.ha&&this.ca.$){this.I();a.preventDefault?a.preventDefault():a.returnValue=!1;c.$=!1;b.J.x=0;b.J.y=0;const m=(new Date).getTime();let q;q=Math.abs(b.start.x-b.A.x)+Math.abs(b.start.y-b.A.y);400>m-c.startTime&&
0<=q&&20>q&&this.pa(a.target)&&(q=Math.abs(b.ra.x-b.A.x)+Math.abs(b.ra.y-b.A.y),a=this.Rb(this.M.x,this.M.y),b.ra.x=b.A.x,b.ra.y=b.A.y,a&&this.jf(a),700>m-this.kb&&0<=q&&20>q?(a?this.kf(a):e.Hc&&this.qc(),this.kb=0):this.kb=m)}}Fe(a){var b=this.margin;const c=this.zoom;var e=this.U,m=this.m;if(!m.cd&&this.pa(a.target)){let q=a.detail?-1*a.detail:a.wheelDelta/40;m.pe&&(q=-q);const n=this.M.x-b.left.v-.5*e.width;b=this.M.y-b.top.v-.5*e.height;e=c.o;this.yc((0<q?1:-1)*m.Ye,!0);m=1/(c.viewport*c.o)-1/
(c.viewport*e);c.cx+=n*m;c.cy+=b*m;this.D=!0;a.preventDefault?a.preventDefault():a.returnValue=!1;this.I()}}Ph(a){var b=this.margin;const c=this.zoom,e=this.ya,m=this.ca;var q=this.m,n=this.H;this.rc=null;const t=a.touches;var r=this.Ga();this.M.x=t[0].pageX-r.x+b.left.v;this.M.y=t[0].pageY-r.y+b.top.v;if(!q.ha){if(1==t.length&&!m.$&&t[0]&&(m.startTime=(new Date).getTime(),m.start.x=t[0].pageX,m.start.y=t[0].pageY,m.A.x=t[0].pageX,m.A.y=t[0].pageY,q=this.la=t[0].target,this.pa(q)&&(this.sf(t[0].pageX,
t[0].pageY),m.Lc=t[0].identifier,m.$=!0,a.preventDefault(),this.I(),(r=this.Rb(m.start.x,m.start.y))&&this.F!=r&&(this.bb(r),this.rc=r,this.W&&(this.W.hotspotProxyOver&&this.W.hotspotProxyOver(this.F.id),this.u("hsproxyover",{id:this.F.id,url:this.F.url})),0<n.mode&&(n.R=1,this.F.R=1,this.D=!0),this.sc(m.start.x-b.left.v,m.start.y-b.top.v,!0))),q)){b=!1;if(null!=this.ca.pb)for(n=this.ca.pb;n&&n!=this.control;){if(n.onmouseout)n.onmouseout(a);if(n.onmouseleave)n.onmouseleave(a);n=n.parentNode}n=q;
for(r=!0;n&&n!=this.control;)q!=this.ca.pb&&(n.onmouseover&&(n.onmouseover(a),this.pa(a)&&(b=!0)),n.onmouseenter&&(n.onmouseenter(a),this.pa(a)&&(b=!0))),n.onmousedown&&(n.onmousedown(a),r=!1,b=!0),n.onclick&&(r=!1),n=n.parentNode;this.ca.pb=r&&q!=this.ca.pb?q:null;b&&a.preventDefault()}1<t.length&&(m.$=!1);!this.Qc&&2==t.length&&t[0]&&t[1]&&(c.$e=Math.sqrt((t[0].pageX-t[1].pageX)*(t[0].pageX-t[1].pageX)+(t[0].pageY-t[1].pageY)*(t[0].pageY-t[1].pageY)),c.prev=c.o);e.J.x=0;e.J.y=0}}Oh(a){const b=this.margin,
c=this.zoom,e=this.U;var m=this.ca,q=this.m;const n=a.touches,t=this.Ga();this.M.x=n[0].pageX-t.x+b.left.v;this.M.y=n[0].pageY-t.y+b.top.v;if(!q.ha){if(1==n.length&&n[0]&&(m.A.x=n[0].pageX,m.A.y=n[0].pageY,m.$)){a.preventDefault();for(q=0;q<n.length;q++)if(n[q].identifier==m.Lc){this.rf(n[q].pageX,n[q].pageY);break}this.I()}2==n.length&&n[0]&&n[1]&&(m.$=!1,this.Qc||(c.Sd=Math.sqrt((n[0].pageX-n[1].pageX)*(n[0].pageX-n[1].pageX)+(n[0].pageY-n[1].pageY)*(n[0].pageY-n[1].pageY)),m=c.o,this.eb(c.prev/
c.$e*c.Sd),m=1/(c.viewport*c.o)-1/(c.viewport*m),c.cx+=(this.M.x-b.left.v-.5*e.width)*m,c.cy+=(this.M.y-b.top.v-.5*e.height)*m,a.preventDefault()))}}Nh(a){const b=this,c=b.ca,e=b.H;let m=!1;if(!b.m.ha){c.$&&(a.preventDefault(),b.I());var q=(new Date).getTime();let t=!1;var n=Math.abs(c.start.x-c.A.x)+Math.abs(c.start.y-c.A.y);if(0<=n&&20>n){m=!0;if(b.la){for(n=b.la;n&&n!=b.control;){if(n.onclick){let r=n,f=b.hotspot;setTimeout(()=>{let w=b.hotspot;b.hotspot=f;r.onclick(a);b.hotspot=w},0);"hotspot"!=
n.ei&&(t=!0);m=!1}n=n.parentNode}n=Math.abs(c.ra.x-c.A.x)+Math.abs(c.ra.y-c.A.y);if(700>q-b.kb&&0<=n&&20>n){if(b.pa(b.la))if(a.preventDefault(),b.rc)b.kf(b.rc);else if(b.m.Hc){let r=this;setTimeout(function(){r.qc()},1)}if(b.la)for(n=b.la;n&&n!=b.control;)n.ondblclick&&(n.ondblclick(),t=!0,m=!1),n=n.parentNode;b.kb=0}else b.kb=q;c.ra.x=c.A.x;c.ra.y=c.A.y}(q=b.Rb(b.M.x,b.M.y))&&m&&(b.jf(q),m=!0);c.ra.x=c.A.x;c.ra.y=c.A.y}if(b.la)for(n=b.la;n&&n!=b.control;)c.pb!=b.la&&(n.onmouseout&&(n.onmouseout(a),
t=!0),n.onmouseleave&&(n.onmouseleave(a),t=!0)),n.onmouseup&&(n.onmouseup(a),t=!0),n=n.parentNode;b.F!=b.ga&&(0<e.mode&&(e.R=0,b.F.R=0,b.D=!0),b.bb(b.ga),b.sc(-1,-1,!0));t&&a.preventDefault();b.la=null;c.$=!1;this.rc=null}}Mh(a){this.m.ha||(a.preventDefault(),this.ca.$=!1)}Yd(a){const b=this.margin,c=this.zoom,e=this.m;this.Qc=!0;this.Eb=1;let m=this.Ga();a.pageX&&(this.M.x=a.pageX-m.x+b.left.v,this.M.y=a.pageY-m.y+b.top.v);e.ha||(a.touches?(this.la=a.touches.target,this.la==this.control&&(a.preventDefault(),
c.prev=c.o,this.I())):(a.preventDefault(),c.prev=c.o,this.I()))}Qf(a){const b=this.margin,c=this.zoom,e=this.U;if(!this.m.ha&&this.pa(a.target)){a.preventDefault();var m=c.o;this.eb(a.scale*c.prev);a=1/(c.viewport*c.o)-1/(c.viewport*m);c.cx+=(this.M.x-b.left.v-.5*e.width)*a;c.cy+=(this.M.y-b.top.v-.5*e.height)*a;this.I()}}Pg(a){const b=this.zoom;var c=this.U;if(!this.m.ha){var e=this.Ga();if(this.ib()){var m=a.screenX-.5*c.width;c=a.screenY-.5*c.height}else m=a.pageX-e.x-.5*c.width,c=a.pageY-e.y-
.5*c.height;a.preventDefault();1!=a.scale&&(this.Eb*=a.scale,a=b.o,this.eb(this.Eb*b.prev),a=1/(b.viewport*b.o)-1/(b.viewport*a),b.cx+=m*a,b.cy+=c*a,this.I())}}Xd(a){const b=this.Db;this.m.ha||(b.fov.active=!1,this.pa(a.target)&&(a.preventDefault(),this.I(),this.lb&&this.lb.reset&&this.lb.reset()))}Jg(a){this.m.Za||(a=a?a:window.event,this.ac=a.keyCode,this.I())}Kg(){this.ac=0;this.m.Za||this.I()}Rg(){this.ac=0;this.m.Za||this.I()}zd(a){this.m.ea?this.Cd(a):this.Bd(a)}Ad(a){this.m.ea?this.Bd(a):this.Cd(a)}fb(){const a=
this.j,b=this.zoom;var c=this.U,e=this.m;b.ec&&(b.max=a.height/c.height*b.ec);if(e.Aa){for(;0>a.x;)a.x+=a.G;for(;a.x>=a.G;)a.x-=a.G}else 0>a.x&&(a.x=0),a.x>=a.G&&(a.x=a.G-1);if(e.Ba){for(;0>a.y;)a.y+=a.L;for(;a.y>=a.L;)a.y-=a.L}else 0>a.y&&(a.y=0),a.y>=a.L&&(a.y=a.L-1);a.state>=a.Ha&&(a.state=a.Ha-1);0>a.state&&(a.state=0);b.o=Math.max(b.min,Math.min(b.max,b.o));e.Qb&&(e.ab=1<b.o,this.u("viewmodechanged",{}));c.width>=b.viewport*b.o*a.width?b.cx=0:(e=(a.width*b.viewport*b.o-c.width)/(b.o*b.viewport*
2),b.cx=Math.max(-e,b.cx),b.cx=Math.min(+e,b.cx));c.height>=b.viewport*b.o*a.height?b.cy=0:(c=(a.height*b.viewport*b.o-c.height)/(b.o*b.viewport*2),b.cy=Math.max(-c,b.cy),b.cy=Math.min(+c,b.cy));this.u("checklimits",{x:a.x,y:a.y,state:a.state})}Bc(a,b){const c=this.j;this.I();c.state!=a&&(c.state=a,0<b&&(a=1/(20*b),this.oa?(this.Ma.style.visibility="inherit",this.fa.style.transition="opacity "+a+"s linear",this.vb==this.oa?(this.fa.style.opacity="0.0",this.vb=this.Fc):(this.fa.style.opacity="1.0",
this.vb=this.oa)):(this.xa.style.visibility="inherit",this.Y.style.transition="opacity "+a+"s linear",this.Oa==this.Y?(this.Y.style.opacity="0.0",this.Oa=this.xa):(this.Y.style.opacity="1.0",this.Oa=this.Y)),this.ud()),this.D=!0)}ke(){return this.j.state}Sc(a,b,c){return this.Kc(this.j.path+"/img_"+c+"_"+b+"_"+a+"."+this.j.ext)}ud(){this.Ya?(this.ef(),this.td()):(this.fb(),this.Wh())}Wh(){const a=this;if(a.Yb){var b,c,e=a.j,m=a.zoom,q=Math.floor(e.x),n=Math.floor(e.y),t=e.state,r=b=!1;if(e.Ea!=q||
e.Fa!=n||e.va!=t){if(0<e.levels.length)for(c=0;c<e.levels.length;c++)b=e.levels[c],b.cache?b.sd[a.ne()]=b.Sa:b.Sa=[];e.Ea=q;e.Fa=n;e.va!=t&&(e.va=t,r=!0);if(0<e.levels.length&&a.oa)for(c=0;c<e.levels.length;c++)b=e.levels[c],b.cache&&(b.Sa=b.sd[a.ne()],b.Sa||(b.Sa=[]));else 0<e.levels.length?a.Oa.setAttribute("src",a.rd(q,n,t,e.levels.length-1,0,0)):a.Oa.setAttribute("src",a.Sc(q,n,t)),a.Oa.onload=function(){this.Cg=!0;a.D=!0;a.Xa=!0},a.Oa.Cg=!1;b=!0}this.m.Id&&m.o!=m.A&&1==m.o&&(this.m.Qb=!0,this.u("viewmodechanged",
{}));if(b||a.Xa||m.o!=m.A||m.cx!=m.cc||m.cy!=m.dc)a.lf(),this.u("positionchanged",{}),a.Xa=!1;r&&this.u("viewstatechanged",{})}}Tg(){const a=this.j,b=this.zoom,c=this.U,e=this.H;if(this.S){if(e.ye!=e.mode||0<e.ba.length)e.ye=e.mode,this.S.style.visibility=0<e.mode||0<e.ba.length?"inherit":"hidden";if(0<=e.mode||0<this.H.ba.length){if(!this.Ec)try{this.Ec=this.S.getContext("2d")}catch(v){}if(this.Ec){const v=this.Ec;if(v.width!=c.width||v.height!=c.height)v.width=c.width,v.height=c.height;v.clear?
v.clear():v.clearRect(0,0,this.S.width,this.S.height);var m=1;0>=e.mode&&(m=0);3==e.mode&&(m=e.P);for(var q=0;q<this.K.length;q++){var n=this.K[q];if("poly"==n.type){var t=m;2==e.mode&&(t=n.P);var r=e.ba.indexOf(n.id);-1!=r&&(t=e.ia[r]);for(var f=0;f<n.mb.length;f++){var w=n.mb[f];if((w.Cc==a.Ea||n.reuse&1)&&(w.kd==a.Fa||n.reuse&2)&&(w.state==a.va||n.reuse&4))for(let y=0;y<w.Gb.length;y++){const A=w.Gb[y];v.fillStyle=this.Ab(n.backgroundcolor,n.backgroundalpha*t);v.strokeStyle=this.Ab(n.bordercolor,
n.borderalpha*t);if(0<A.vertices.length){v.beginPath();for(let C=0;C<A.vertices.length;C++){var x=A.vertices[C];r=b.viewport*b.o*(b.cx+(x.x-.5)*a.width)+.5*c.width;x=b.viewport*b.o*(b.cy+(x.y-.5)*a.height)+.5*c.height;0==C?v.moveTo(r,x):v.lineTo(r,x)}v.closePath();v.stroke();v.fill()}}}}}}}}}Rb(a,b){var c=this.margin;const e=this.j;var m=this.zoom,q=this.U;const n=this.H,t=this.K;let r=-1;a=((a-c.left.v-.5*q.width)/(m.viewport*m.o)-m.cx)/e.width+.5;b=((b-c.top.v-.5*q.height)/(m.viewport*m.o)-m.cy)/
e.height+.5;for(c=0;c<t.length;c++)if(m=t[c],"poly"==m.type&&m.mb&&(0<=n.mode||0<this.H.ba.length&&-1!=this.H.ba.indexOf(m.id)))for(q=0;q<m.mb.length;q++){const w=m.mb[q];if((w.Cc==e.Ea||m.reuse&1)&&(w.kd==e.Fa||m.reuse&2)&&(w.state==e.va||m.reuse&4))for(let x=0;x<w.Gb.length;x++){const v=w.Gb[x];if(0<v.vertices.length){let y;var f=void 0;let A,C;A=!1;y=0;for(f=v.vertices.length-1;y<v.vertices.length;f=y++)C=v.vertices[y],f=v.vertices[f],C.y>b!=f.y>b&&a<(f.x-C.x)*(b-C.y)/(f.y-C.y)+C.x&&(A=!A);A&&
(r=c)}}}return 0<=r?t[r]:!1}xf(){const a=this.K;for(let b=0;b<a.length;b++)if("point"==a[b].type&&(this.W&&this.W.addSkinHotspot&&(a[b].O=new this.W.addSkinHotspot(a[b])),a[b].O&&a[b].O.__div)){const c=this.Z.firstChild;c?this.Z.insertBefore(a[b].O.__div,c):this.Z.appendChild(a[b].O.__div)}}td(){const a=this.K,b=this.margin,c=this.j,e=this.zoom,m=this.U;for(let n=0;n<a.length;n++){const t=a[n];let r,f;if("point"==t.type){let w=!1;if(this.Ya){var q=new this.THREE.Vector3(t.Fb.x,t.Fb.y,t.Fb.z);this.$a&&
(console.log(q),q.applyMatrix4(this.Og.matrix),console.log(q),q.applyMatrix4(this.$a.matrix),(w=0<=q.z)?(q.length(),q.project(this.camera),r=m.width*(.5+q.x/2),f=m.height*(.5-q.y/2)):f=r=0)}else for(f=r=0,q=0;q<t.locations.length;q++){const x=t.locations[q];(x.column==c.Ea||t.reuse&1)&&(x.row==c.Fa||t.reuse&2)&&(x.state==c.va||t.reuse&4)&&(w=!0,r=e.viewport*e.o*(e.cx+x.x*c.width-c.width/2)+m.width/2,f=e.viewport*e.o*(e.cy+x.y*c.height-c.height/2)+m.height/2)}t.O&&t.O.__div&&(t.O.__div.style.transition=
"none",w?(t.O.__div.style.left=b.left.v+r+"px",t.O.__div.style.top=b.top.v+f+"px",t.O.__div.ggVisible&&(t.O.__div.style.visibility="visible")):(t.O.__div.style.left="-100px",t.O.__div.style.top="-100px",t.O.__div.style.visibility="hidden"))}}this.u("hotspotsupdated",{})}ce(a){for(var b=0;b<this.K.length;b++){let c=this.K[b];if(c.id==a)return b={},b.id=a,b.url=c.url,b.target=c.target,b.title=c.title,b.description=c.description,b.skinid=c.zh,c.Jf&&(b.customimage=c.Jf,b.customimagewidth=c.bi,b.customimageheight=
c.ai),c.O&&c.O.__div&&(b.div=c.O.__div),b}}tf(){const a=this;setTimeout(function(){a.tf()},200);5<a.jd&&(a.requestAnimationFrame=function(){return function(b){window.setTimeout(b,10)}},a.Uc=!0,a.tc());a.jd++}tc(){const a=this;var b=a.j,c=a.fov;var e=a.zoom;var m=a.Db,q=a.Sg;const n=a.ub,t=a.Ca;var r=a.U;var f=a.ya;const w=a.ca;var x=a.m;const v=a.H,y=a.K;var A=Date.now();let C=.01*(A-t.ad);100<C&&(C=100);t.ad=A;this.u("timer",{});this.vd&&(this.wd(),this.vd=!1);a.Uc?setTimeout(function(){a.tc()},
1E3/60):requestAnimationFrame(function(){a.tc()});a.jd=0;if(w.$){if(2==x.mode)r=f.A.x-f.start.x,f=f.A.y-f.start.y,a.yd(r*x.sensitivity/300,f*x.sensitivity/300);else if(3==x.mode){const z=a.Ga();let D;x.ea?(A=(f.A.x-z.x)/r.width,D=(f.A.y-z.y)/r.height):(D=(f.A.x-z.x)/r.width,A=(f.A.y-z.y)/r.height);x.Lb&&(D=1-D);x.Mb&&(A=1-A);x=Math.floor((1-D)*b.G);f=Math.floor((1-A)*b.L);0>x&&(x=0);x>=b.G&&(x=b.G-1);0>f&&(f=0);f>=b.L&&(f=b.L-1);a.We(x,f)}else m.J.x=.4*(f.A.x-m.A.x),m.J.y=.4*(f.A.y-m.A.y),m.A.x+=
m.J.x,m.A.y+=m.J.y,a.yd(m.J.x*x.sensitivity/10,m.J.y*x.sensitivity/10),m.fov.active&&a.xc(.4*(m.fov.Lf-100*e.o));a.D=!0}!m.enabled||0==m.J.x&&0==m.J.y||w.$||(m.J.x*=.9,m.J.y*=.9,.1>m.J.x*m.J.x+m.J.y*m.J.y?(m.J.x=0,m.J.y=0):(a.yd(m.J.x,m.J.y),a.D=!0));if(!a.ve&&a.Yb){for(x=f=0;x<a.Na.length;x++)a.Na[x].complete&&a.Na[x].src!=a.Mf&&f++;a.oe&&(a.oe=!1);f==a.Na.length?(a.ic=1,a.ve=!0,a.C&&a.C.ggLoaded&&a.C.ggLoaded(),this.u("imagesready",{})):a.ic=f/(1*a.Na.length);this.u("downloadprogress",{percentLoaded:this.ic})}n.active?
(b.dx=n.x-b.x,b.dx>b.G/2&&(b.dx-=b.G),b.dx<b.G/2*-1&&(b.dx+=b.G),b.dy=n.y-b.y,a.fov.d=(n.fov-100*e.o)/10,c=Math.sqrt(b.dx*b.dx+b.dy*b.dy+c.d*c.d),10*c<n.speed?(n.active=!1,b.dx=0,b.dy=0,a.fov.d=0,b.x=Number(n.x),b.y=Number(n.y),e.o=n.fov/100):(c=c>5*n.speed?n.speed/c:.2,b.dx*=c,b.dy*=c,a.fov.d*=c),b.x+=C*b.dx,b.y+=C*b.dy,b.x>=b.G&&(b.x-=b.G,n.x-=b.G),0>b.x&&(b.x+=b.G,n.x+=b.G),b.y>=b.L&&(b.y-=b.L,n.y-=b.L),0>b.y&&(b.y+=b.L,n.y+=b.L),e.o+=a.fov.d/10,0<n.Ia&&.5>a.fov.d&&(c=.5-e.cx/b.width,m=.5-e.cy/
b.height,r=(n.cx-c)/n.Ia,f=(n.cy-m)/n.Ia,e.cx=(.5-c-r)*b.width,e.cy=(.5-m-f)*b.height,n.Ia--,n.Ia&&(n.active=!0)),e=new Date,a.bc=e.getTime(),a.D=!0):t.active?(b.dx=.95*b.dx+.05*t.speed,b.x+=b.dx*C,t.pingpong&&(0>b.x||b.x>=b.G)&&(t.speed=-t.speed,b.dx=-b.dx,b.x+=2*b.dx*C),a.D=!0):(t.enabled&&(e=new Date,e=e.getTime()-a.bc,!w.$&&0<t.delay&&e>1E3*t.delay&&(t.active=!0,a.u("autorotatechanged",{}),b.dx=0,b.dy=0)),!m.enabled||0!=a.ac||w.$||0==b.dx&&0==b.dy&&0==a.fov.d||(b.dx*=.9,b.dy*=.9,c.d*=.9,b.x+=
b.dx,b.y+=b.dy,a.yc(c.d),1E-4>b.dx*b.dx+b.dy*b.dy&&(b.dx=0,b.dy=0,c.d=0),a.D=!0));q.Af&&(e=new Date,q.Sb?e.getTime()-q.Jc>=1E3*q.delay&&(q.Sb=!1):(q.current+=q.ua,0>q.current&&(q.current=0,q.ua=-q.ua,q.Sb=!0,q.Jc=e.getTime()),1<q.current&&(q.current=1,q.ua=-q.ua,q.Sb=!0,q.Jc=e.getTime())));if(0<v.mode||0<v.ba.length){if(0<v.ba.length){for(x=0;x<v.ba.length;x++)v.sa[x]!=v.ia[x]?v.sa[x]>v.ia[x]?(v.ia[x]+=.05,v.sa[x]<v.ia[x]&&(v.ia[x]=v.sa[x])):(v.ia[x]-=.05,v.sa[x]>v.ia[x]&&(v.ia[x]=v.sa[x])):0==v.ia[x]&&
-1!=v.oc.indexOf(v.ba[x])&&(v.oc.splice(v.oc.indexOf(v.ba[x]),1),v.ba.splice(x,1),v.sa.splice(x,1),v.ia.splice(x,1));a.D=!0}if(2==v.mode)for(b=0;b<y.length;b++)q=y[b],"poly"==q.type&&q.R!=q.P&&(q.R>q.P?(q.P+=v.ua,q.R<q.P&&(q.P=q.R)):(q.P-=v.ua,q.R>q.P&&(q.P=q.R)),a.D=!0);3==v.mode&&v.R!=v.P&&(v.R>v.P?(v.P+=v.ua,v.R<v.P&&(v.P=v.R)):(v.P-=v.ua,v.R>v.P&&(v.P=v.R)),a.D=!0)}a.D&&(a.D=!1,a.ud(),a.Cb&&a.Tg())}nf(){const a=this;setTimeout(function(){a.cb(0)},10);setTimeout(function(){a.cb(0)},100)}zf(){const a=
this;var b=a.Z;a.control=b;a.nf();a.Ca.ad=Date.now();setTimeout(function(){a.tc()},10);setTimeout(function(){a.tf()},200);setTimeout(function(){a.sb();a.ud()},10);b.addEventListener&&(b.addEventListener("touchstart",c=>{a.Ph(c)},!1),b.addEventListener("touchmove",c=>{a.Oh(c)},!1),b.addEventListener("touchend",c=>{a.Nh(c)},!1),b.addEventListener("touchcancel",c=>{a.Mh(c)},!1),b.addEventListener("pointerdown",c=>{a.He(c)},!1),b.addEventListener("MSPointerDown",c=>{a.He(c)},!1),b.addEventListener("MSGestureStart",
c=>{a.Yd(c)},!1),b.addEventListener("MSGestureEnd",c=>{a.Xd(c)},!1),b.addEventListener("MSGestureChange",c=>{a.Pg(c)},!1),b.addEventListener("gesturestart",c=>{a.Yd(c)},!1),b.addEventListener("gesturechange",c=>{a.Qf(c)},!1),b.addEventListener("gestureend",c=>{a.Xd(c)},!1),b.addEventListener("mousedown",c=>{a.Ee(c)},!1),b.addEventListener("mousemove",c=>{a.De(c)},!1),a.Y.addEventListener("mousedown",c=>{a.Ee(c)},!1),a.Y.addEventListener("mousemove",c=>{a.De(c)},!1),document.addEventListener("mouseup",
c=>{a.Lg(c)},!1),b.addEventListener("mousewheel",c=>{a.Fe(c)},!1),b.addEventListener("DOMMouseScroll",c=>{a.Fe(c)},!1),document.addEventListener("keydown",c=>{a.Jg(c)},!1),document.addEventListener("keyup",()=>{a.Kg()},!1),window.addEventListener("orientationchange",()=>{a.nf()},!1),window.addEventListener("resize",()=>{a.sb()},!1),window.addEventListener("blur",()=>{a.Rg()},!1),a.B.addEventListener("webkitfullscreenchange",()=>{a.hc()},!1),document.addEventListener("mozfullscreenchange",()=>{a.hc()},
!1),window.addEventListener("webkitfullscreenchange",()=>{a.hc()},!1),document.addEventListener("MSFullscreenChange",()=>{a.hc()},!1));b.oncontextmenu=function(c){void 0===c&&(c=window.event);return c.target&&!a.pa(c.target)?!0:c.ctrlKey?!0:(c=a.jg(c),a.xh(c.x,c.y),!1)}}cb(a){const b=this.margin;this.qa!=a&&(this.qa=a,this.Xa=this.D=!0);if(this.qa){try{this.B.webkitRequestFullScreen?this.B.webkitRequestFullScreen():this.B.mozRequestFullScreen?this.B.mozRequestFullScreen():this.B.msRequestFullscreen?
this.B.msRequestFullscreen():this.B.requestFullScreen?this.B.requestFullScreen():this.B.requestFullscreen&&this.B.requestFullscreen()}catch(m){}this.B.style.position="absolute";a=this.Ga();var c=0,e=0;"number"==typeof window.pageYOffset?(e=window.pageYOffset,c=window.pageXOffset):document.body&&(document.body.scrollLeft||document.body.scrollTop)?(e=document.body.scrollTop,c=document.body.scrollLeft):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&
(e=document.documentElement.scrollTop,c=document.documentElement.scrollLeft);this.B.style.left=Math.round(c-a.x+b.left.v)+"px";this.B.style.top=Math.round(e-a.y+b.top.v)+"px";document.body.style.overflow="hidden";this.C&&this.C.ggEnterFullscreen&&this.C.ggEnterFullscreen();this.u("fullscreenenter",{})}else{try{document.webkitIsFullScreen?document.webkitCancelFullScreen():document.mozFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.fullScreen&&
(document.cancelFullScreen?document.cancelFullScreen():document.exitFullscreen&&document.exitFullscreen())}catch(m){}this.B.style.position="relative";this.B.style.left="0px";this.B.style.top="0px";document.body.style.overflow="";this.C&&this.C.ggExitFullscreen&&this.C.ggExitFullscreen();this.u("fullscreenexit",{})}this.u("playerstatechanged",{});this.sb()}Ze(a,b,c){const e=this.Ca;e.enabled=!0;e.active=!0;a&&0!=a&&(e.speed=a);b&&(e.delay=b);c&&(e.pingpong=1==c);this.u("autorotatechanged",{})}af(){const a=
this.Ca;a.active=!1;a.enabled=!1;this.u("autorotatechanged",{})}hf(){const a=this.Ca;a.enabled=!a.active;a.active=a.enabled;this.u("autorotatechanged",{})}Zf(){return this.Ca.active}Od(a){0==a&&(this.m.ab=!1);1==a&&(this.m.ab=!0);2==a&&(this.m.ab=this.m.ab?!1:!0);this.m.Qb=3==a;this.u("viewmodechanged",{});this.u("playerstatechanged",{})}je(){return 1==this.m.ab?1:0}gb(a){let b=[];a="*"==a?"^.*$":"#"==a.substring(0,1)?a.substring(1):"^"+a+"$";let c=new RegExp(a,"");Object.keys(this.xd).forEach(e=>
{c.test(e)&&b.push(this.xd[e])});return b}fe(a){a=this.gb(a);return 0<a.length?a[0]:null}Zg(a,b){let c=this;b.addEventListener("ended",function(e){c.u("videoended",{video:e.target})});b.addEventListener("pause",function(e){c.u("videopaused",{video:e.target})});b.addEventListener("play",function(e){c.u("videostarted",{video:e.target})});this.xd[a]=b}jc(a){var b=null;a=this.gb(a);for(var c=0;c<a.length;c++)b=a[c].play();return b}Je(a,b){let c=this.gb(a);for(var e=0;e<c.length;e++)c[e].paused?this.jc(a,
b):this.fd(a)}Ke(a,b){let c=this.gb(a);for(var e=0;e<c.length;e++)c[e].paused?this.jc(a,b):this.od(a)}fd(a){try{let b,c=this.gb(a);for(b=0;b<c.length;b++)c[b].pause()}catch(b){}}od(a){let b;try{let c=this.gb(a);for(b=0;b<c.length;b++){let e=c[b];e.pause();e.currentTime=0}}catch(c){}}xh(a,b){let c=this,e=[];if(c.m.Pd){let m={style:"text-align: left;margin: 0;padding: 5px 20px;vertical-align: left;cursor: pointer;",onclick:function(){c.qc()}};m.innerHTML=c.ib()?this.Ta("Exit Fullscreen"):this.Ta("Enter Fullscreen");
e.push(m)}c.yh(a,b,e)}Dc(a){const b=this.jh;(this.V=document.getElementById(a))?(this.V.innerHTML="",this.B=document.createElement("div"),b&&this.B.setAttribute("id","viewport"),this.B.setAttribute("style","top:\t0px;left: 0px;-ms-touch-action: none;touch-action: none;position:relative;max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.V.appendChild(this.B),this.X=document.createElement("div"),
b&&this.X.setAttribute("id","viewer"),a="top:\t0px;left: 0px;overflow: hidden;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.na+"user-select: none;"),this.X.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.B.appendChild(this.X),this.xa=document.createElement("img"),b&&this.xa.setAttribute("id","objectimage2"),this.xa.setAttribute("galleryimg",
"false"),a="top:\t0px;left: 0px;position:absolute;visibility: hidden;-ms-touch-action: none;touch-action: none;"+(this.na+"user-select: none;"),this.xa.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.X.appendChild(this.xa),this.Y=document.createElement("img"),b&&this.Y.setAttribute("id","objectimage"),this.Y.setAttribute("galleryimg","false"),a="top:\t0px;left: 0px;position:absolute;-ms-touch-action: none;touch-action: none;"+
(this.na+"user-select: none;"),this.Y.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.X.appendChild(this.Y),this.Oa=this.Y,this.Ma=document.createElement("canvas"),b&&this.Ma.setAttribute("id","objectcanvas2"),a="top:\t0px;left: 0px;width:  100px;height: 100px;visibility: hidden;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.na+"user-select: none;"),
this.Ma.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.X.appendChild(this.Ma),this.fa=document.createElement("canvas"),b&&this.fa.setAttribute("id","objectcanvas"),a="top:\t0px;left: 0px;width:  100px;height: 100px;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.na+"user-select: none;"),this.fa.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),
this.X.appendChild(this.fa),this.Pa=document.createElement("div"),b&&this.Pa.setAttribute("id","hotspottext"),this.Pa.setAttribute("style","top:\t0px;left: 0px;position:absolute;padding: 3px;visibility: hidden;z-index: 1100;"),this.Pa.classList.add("ggskin"),this.Pa.classList.add("ggdefaulthotspot"),this.Pa.innerHTML=" Hotspot text!",this.X.appendChild(this.Pa),this.Z=document.createElement("div"),b&&this.Z.setAttribute("id","hotspots"),a="top:\t0px;left: 0px;width:  100px;height: 100px;overflow: hidden;position:absolute;z-index: 1000;"+
(this.na+"user-select: none;"),this.Z.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.B.appendChild(this.Z),this.S=document.createElement("canvas"),b&&this.S.setAttribute("id","hotspotcanvas"),a="top:\t0px;left: 0px;width:  100px;height: 100px;overflow: hidden;position:absolute;z-index: 900;"+(this.na+"user-select: none;"),this.S.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),
this.B.appendChild(this.S),this.divSkin=this.C=this.Z):alert("container not found!")}hd(a){this.bb(this.ga);const b=this.Db,c=this.config,e=this.j,m=this.zoom,q=this.m,n=this.Ca,t=this.H;var r=a.firstChild;a=r.firstChild;null==a&&(a=r.nextSibling.firstChild);for(var f;a;){"customproperty"==a.nodeName&&this.Of(a);if("view"==a.nodeName)for(r=a.firstChild;r;){"start"==r.nodeName&&(f=r.getAttributeNode("column"),e.nb=Number(f?f.nodeValue:0),e.x=e.nb,f=r.getAttributeNode("row"),e.ob=Number(f?f.nodeValue:
0),e.y=e.ob,f=r.getAttributeNode("state"),e.pc=Number(f?f.nodeValue:0),e.state=e.pc);"zoom"==r.nodeName&&(f=r.getAttributeNode("min"),m.min=1*(f?f.nodeValue:1),f=r.getAttributeNode("default"),m.Wa=1*(f?f.nodeValue:1),m.o=m.Wa,f=r.getAttributeNode("max"),m.max=1*(f?f.nodeValue:1),f=r.getAttributeNode("maxpixel"),m.ec=1*(f?f.nodeValue:0),f=r.getAttributeNode("centerx"),m.cx=1*(f?f.nodeValue:0),f=r.getAttributeNode("centery"),m.cy=1*(f?f.nodeValue:0));"limits"==r.nodeName&&(f=r.getAttributeNode("panmin"),
this.pan.min=1*(f?f.nodeValue:0),f=r.getAttributeNode("panmax"),this.pan.max=1*(f?f.nodeValue:360),f=r.getAttributeNode("tiltmin"),this.ja.min=1*(f?f.nodeValue:0),f=r.getAttributeNode("tiltmax"),this.ja.max=1*(f?f.nodeValue:90));if("viewer"==r.nodeName){if(f=r.getAttributeNode("background"))c.background=1==f.nodeValue;if(f=r.getAttributeNode("backgroundcolor"))c.ma=1*f.nodeValue;if(f=r.getAttributeNode("imagescaling"))m.Ne=1*f.nodeValue}r=r.nextSibling}if("autorotate"==a.nodeName){this.Ub&&(n.enabled=
!1);if(f=a.getAttributeNode("start"))n.enabled=1==f.nodeValue;if(f=a.getAttributeNode("pingpong"))n.pingpong=1==f.nodeValue;if(f=a.getAttributeNode("speed"))n.speed=1*f.nodeValue;if(f=a.getAttributeNode("delay"))n.delay=1*f.nodeValue;n.active=n.enabled;(f=a.getAttributeNode("onlyonce"))&&0<f.nodeValue&&(r=e.nb,r=0<n.speed?r+(f.nodeValue*e.G+.5):r-(f.nodeValue*e.G+.5),this.moveTo(r,e.ob,0,Math.abs(n.speed)))}if("input"==a.nodeName){if(f=a.getAttributeNode("columns"))e.G=1*f.nodeValue;if(f=a.getAttributeNode("rows"))e.L=
1*f.nodeValue;if(f=a.getAttributeNode("states"))e.Ha=1*f.nodeValue;if(f=a.getAttributeNode("statestitles"))this.nd=f.value.split("|");if(f=a.getAttributeNode("width"))e.width=1*f.nodeValue;if(f=a.getAttributeNode("height"))e.height=1*f.nodeValue;if(f=a.getAttributeNode("fileextension"))e.ext=f.nodeValue;if(f=a.getAttributeNode("hasalpha"))e.Rc=1==f.nodeValue;if(f=a.getAttributeNode("imagepath"))e.path=f.nodeValue;if(f=a.getAttributeNode("leveltileurl"))e.ze=f.nodeValue;if(f=a.getAttributeNode("leveltilesize"))e.da=
Number(f.nodeValue);if(f=a.getAttributeNode("overlap"))e.bd=f.nodeValue;if(f=a.getAttributeNode("preload"))e.preload=1==f.nodeValue;e.levels=[];for(r=a.firstChild;r;){if("level"==r.nodeName){var w={};f=r.getAttributeNode("width");w.width=1*(f?f.nodeValue:1);f=r.getAttributeNode("height");w.height=1*(f?f.nodeValue:1);f=r.getAttributeNode("preload");w.cache=!1;f&&(w.cache=1==f.nodeValue);w.Ra=Math.floor((w.width+e.da-1)/e.da);w.Ob=Math.floor((w.height+e.da-1)/e.da);w.Sa=[];w.sd=[];e.levels.push(w)}r=
r.nextSibling}}if("control"==a.nodeName&&this.Ub){if(f=a.getAttributeNode("simulatemass"))b.enabled=1==f.nodeValue;if(f=a.getAttributeNode("locked"))q.ha=1==f.nodeValue;f&&(q.Za=1==f.nodeValue);if(f=a.getAttributeNode("lockedmouse"))q.ha=1==f.nodeValue;if(f=a.getAttributeNode("lockedkeyboard"))q.Za=1==f.nodeValue;if(f=a.getAttributeNode("lockedwheel"))q.cd=1==f.nodeValue;if(f=a.getAttributeNode("invertwheel"))q.pe=1==f.nodeValue;if(f=a.getAttributeNode("speedwheel"))q.Ye=1*f.nodeValue;if(f=a.getAttributeNode("sensitifity"))q.sensitivity=
1*f.nodeValue;if(f=a.getAttributeNode("sensitivity"))q.sensitivity=1*f.nodeValue;if(f=a.getAttributeNode("wrapx"))q.Aa=1==f.nodeValue;if(f=a.getAttributeNode("wrapy"))q.Ba=1==f.nodeValue;if(f=a.getAttributeNode("revx"))q.Lb=1==f.nodeValue;if(f=a.getAttributeNode("revy"))q.Mb=1==f.nodeValue;if(f=a.getAttributeNode("swapxy"))q.ea=1==f.nodeValue;if(f=a.getAttributeNode("dblclickfullscreen"))q.Hc=1==f.nodeValue;if(f=a.getAttributeNode("automovemode"))q.Qb=q.Id=1==f.nodeValue;if(f=a.getAttributeNode("controller"))q.mode=
1*f.nodeValue;if(f=a.getAttributeNode("contextfullscreen"))this.m.Pd=1==f.nodeValue;if(f=a.getAttributeNode("hideabout"))this.m.Zb=1==f.nodeValue;for(r=a.firstChild;r;)"menulink"==r.nodeName&&(w={text:"",url:""},f=r.getAttributeNode("text"),w.text=f.nodeValue,f=r.getAttributeNode("url"),w.url=f.nodeValue,this.fc.push(w)),r=r.nextSibling}if("hotspots"==a.nodeName)for(r=a.firstChild;r;){if("label"==r.nodeName){w=t.pd;if(f=r.getAttributeNode("enabled"))w.enabled=1==f.nodeValue;if(f=r.getAttributeNode("width"))w.width=
1*f.nodeValue;if(f=r.getAttributeNode("height"))w.height=1*f.nodeValue;if(f=r.getAttributeNode("textcolor"))w.qd=1*f.nodeValue;if(f=r.getAttributeNode("textalpha"))w.df=1*f.nodeValue;if(f=r.getAttributeNode("background"))w.background=1==f.nodeValue;if(f=r.getAttributeNode("backgroundalpha"))w.Ua=1*f.nodeValue;if(f=r.getAttributeNode("backgroundcolor"))w.ma=1*f.nodeValue;if(f=r.getAttributeNode("border"))w.wc=1*f.nodeValue;if(f=r.getAttributeNode("bordercolor"))w.La=1*f.nodeValue;if(f=r.getAttributeNode("borderalpha"))w.Va=
1*f.nodeValue;if(f=r.getAttributeNode("borderradius"))w.vc=1*f.nodeValue;if(f=r.getAttributeNode("wordwrap"))w.uc=1==f.nodeValue}if("polystyle"==r.nodeName){if(f=r.getAttributeNode("mode"))t.mode=1*f.nodeValue;if(f=r.getAttributeNode("bordercolor"))t.La=1*f.nodeValue;if(f=r.getAttributeNode("backgroundcolor"))t.ma=1*f.nodeValue;if(f=r.getAttributeNode("borderalpha"))t.Va=1*f.nodeValue;if(f=r.getAttributeNode("backgroundalpha"))t.Ua=1*f.nodeValue;if(f=r.getAttributeNode("handcursor"))this.H.Xb=1==
f.nodeValue}if("hotspot"==r.nodeName){var x={type:"point",pan:0,tilt:0,url:"",target:"",id:"",skinid:"",w:100,h:20,customimage:"",customimagewidth:0,customimageheight:0,obj3d:{x:0,y:0,z:0},wordwrap:!1,obj:null,vertices:null};(f=r.getAttributeNode("url"))&&(x.url=f.nodeValue.toString());(f=r.getAttributeNode("target"))&&(x.target=f.nodeValue.toString());(f=r.getAttributeNode("title"))&&(x.title=f.nodeValue.toString());(f=r.getAttributeNode("description"))&&(x.description=f.nodeValue.toString());(f=
r.getAttributeNode("id"))&&(x.id=f.nodeValue.toString());(f=r.getAttributeNode("reuse"))&&(x.reuse=Number(f.nodeValue));(f=r.getAttributeNode("skinid"))&&(x.skinid=f.nodeValue.toString());if(f=r.getAttributeNode("x"))x.Fb.x=parseFloat(f.nodeValue.toString());if(f=r.getAttributeNode("y"))x.Fb.y=parseFloat(f.nodeValue.toString());if(f=r.getAttributeNode("z"))x.Fb.z=parseFloat(f.nodeValue.toString());(f=r.getAttributeNode("customimage"))&&(x.customimage=this.Zd()+f.nodeValue);(f=r.getAttributeNode("customimagewidth"))&&
(x.customimagewidth=Number(f.nodeValue));(f=r.getAttributeNode("customimageheight"))&&(x.customimageheight=Number(f.nodeValue));(f=a.getAttributeNode("width"))&&(x.w=f.nodeValue.toString());(f=a.getAttributeNode("height"))&&(x.h=f.nodeValue.toString());(f=a.getAttributeNode("wordwrap"))&&(x.wordwrap=1==f.nodeValue);x.locations=[];for(w=r.firstChild;w;){if("location"==w.nodeName){var v={column:0,row:0,state:0,x:0,y:0};(f=w.getAttributeNode("column"))&&(v.column=Number(f.nodeValue));(f=w.getAttributeNode("row"))&&
(v.row=Number(f.nodeValue));(f=w.getAttributeNode("state"))&&(v.state=Number(f.nodeValue));(f=w.getAttributeNode("x"))&&(v.x=Number(f.nodeValue));(f=w.getAttributeNode("y"))&&(v.y=Number(f.nodeValue));x.locations.push(v)}w=w.nextSibling}this.K.push(x);this.Vd(r)}if("polyhotspot"==r.nodeName){v={type:"poly",url:"",target:"",id:"",title:"",description:"",skinid:"",reuse:0,w:100,h:20,wordwrap:!1,obj:null,vertices:null,P:0,R:0};(f=r.getAttributeNode("url"))&&(v.url=f.nodeValue.toString());(f=r.getAttributeNode("target"))&&
(v.target=f.nodeValue.toString());(f=r.getAttributeNode("title"))&&(v.title=f.nodeValue.toString());(f=r.getAttributeNode("description"))&&(v.description=f.nodeValue.toString());(f=r.getAttributeNode("id"))&&(v.id=f.nodeValue.toString());(f=r.getAttributeNode("reuse"))&&(v.reuse=Number(f.nodeValue));v.bordercolor=t.La;v.backgroundcolor=t.ma;v.borderalpha=t.Va;v.backgroundalpha=t.Ua;v.handcursor=t.Xb;(f=r.getAttributeNode("bordercolor"))&&(v.bordercolor=1*f.nodeValue);(f=r.getAttributeNode("backgroundcolor"))&&
(v.backgroundcolor=1*f.nodeValue);(f=r.getAttributeNode("borderalpha"))&&(v.borderalpha=1*f.nodeValue);(f=r.getAttributeNode("backgroundalpha"))&&(v.backgroundalpha=1*f.nodeValue);v.mb=[];for(w=r.firstChild;w;){if("polygon"==w.nodeName){x={Cc:0,kd:0,state:0,qf:""};if(f=w.getAttributeNode("vertices")){x.qf=f.nodeValue.toString();f=x.qf.split("|");x.Gb=[];for(var y=0;y<f.length;y++){var A={},C=f[y].split(";");A.vertices=[];for(var z=0;z<C.length;z++){var D=C[z].split(","),F={};F.x=1*D[0];F.y=1*D[1];
A.vertices.push(F)}x.Gb.push(A)}}if(f=w.getAttributeNode("column"))x.Cc=f.nodeValue;if(f=w.getAttributeNode("row"))x.kd=f.nodeValue;if(f=w.getAttributeNode("state"))x.state=f.nodeValue;v.mb.push(x)}w=w.nextSibling}this.K.push(v);this.Vd(r)}r=r.nextSibling}"userdata"==a.nodeName&&(f=a.getAttributeNode("title"),this.ta.title=f?f.nodeValue.toString():"",f=a.getAttributeNode("description"),this.ta.description=f?f.nodeValue.toString():"",f=a.getAttributeNode("author"),this.ta.author=f?f.nodeValue.toString():
"",f=a.getAttributeNode("datetime"),this.ta.datetime=f?f.nodeValue.toString():"",f=a.getAttributeNode("copyright"),this.ta.copyright=f?f.nodeValue.toString():"",f=a.getAttributeNode("source"),this.ta.source=f?f.nodeValue.toString():"",f=a.getAttributeNode("info"),this.ta.information=f?f.nodeValue.toString():"",f=a.getAttributeNode("comment"),this.ta.comment=f?f.nodeValue.toString():"",this.tb.object=this.Pf(a));if("translations"==a.nodeName){for(r=a.firstChild;r;){"json"==r.nodeName&&this.Fd(r.textContent);
if("projecttranslation"==r.nodeName){f={};if(w=r.getAttributeNode("langcode"))f.langCode=w.nodeValue;if(w=r.getAttributeNode("langname"))f.langName=w.nodeValue;this.Le.push(f)}r=r.nextSibling}this.xe||this.Qe(window.navigator.language)}a=a.nextSibling}this.xf();this.D=!0;this.Ub&&this.C&&this.C.ggViewerInit&&this.C.ggViewerInit();this.Ub=!1;this.u("viewerinit",{});this.Yb=!0;this.sb();this.Th();this.Wg();this.u("configloaded",{});this.u("playerstatechanged",{})}Gh(){const a=this,b=a.THREE,c=a.X;(a.camera=
new b.PerspectiveCamera(90,window.innerWidth/window.innerHeight,.05,20)).position.set(0,0,1);var e=a.lc=new b.Scene;const m=new b.HemisphereLight(11657727,12155424,1);e.add(m);e.background=new b.Color(3355443);(new a.uf).setPath("gnome/").load("model.gltf",function(q){q.lc.traverse(f=>{f.isMesh&&(f.material.side=b.DoubleSide)});q=a.Og=q.lc;var n=a.$a=new b.Group;n.add(q);new b.BoxGeometry(.5,.5,.5);new b.MeshBasicMaterial({color:13421772,wireframe:!0});a.lc.add(n);n=(new b.Box3).setFromObject(q);
const t=n.getCenter(new b.Vector3),r=n.getSize(new b.Vector3);console.log(t,r);q.rotateX(-90/(180/Math.PI));q.scale.multiplyScalar(1/Math.max(r.x,r.y,r.z));n.setFromObject(q);n.getCenter(t);n.getSize(r);q.position.copy(t).multiplyScalar(-1);a.update()});e=a.Me=new b.WebGLRenderer({antialias:!0});e.setPixelRatio(window.devicePixelRatio);e.setSize(window.innerWidth,window.innerHeight);e.toneMapping=b.ACESFilmicToneMapping;e.toneMappingExposure=1;e.ii=b.sRGBEncoding;c.appendChild(e.domElement);window.addEventListener("resize",
()=>{a.Hh()})}Hh(){console.log("resize");this.camera.aspect=this.aspect();this.camera.updateProjectionMatrix();const a=this.le();this.Me.setSize(a.width,a.height);this.ef()}ef(){this.$a&&(this.$a.rotation.set(0,0,0),this.$a.updateMatrix(),this.$a.rotateX(this.ja.o*Math.PI/180),this.$a.rotateY(this.pan.o*Math.PI/180));this.Me.render(this.lc,this.camera)}ed(a,b){0<a.length&&window.open(a,b)}kg(){return this.ta}Ud(){}ge(){return{}}Ue(){return!0}}window.object2vrPlayer=L;let h=L.prototype;h._=h.Ta;h.setContainer=
h.hh;h.setLanguage=h.Qe;h.getLanguage=h.dg;h.addTranslations=h.Fd;h.getProjectTranslations=h.tg;h.getVersion=h.Pc;h.readConfigString=h.gd;h.readConfigUrl=h.Xg;h.readConfigUrlAsync=h.Yg;h.readConfigXml=h.hd;h.openUrl=h.ed;h.setMargins=h.lh;h.addListener=h.addListener;h.on=h.addListener;h.removeEventListener=h.removeEventListener;h.off=h.removeEventListener;h.detectBrowser=h.Td;h.getCurrentNode=h.zb;h.getPercentLoaded=h.pg;h.setBasePath=h.gh;h.getBasePath=h.Zd;h.setViewerSize=h.nc;h.getViewerSize=h.le;
h.updateViewerSizeNow=h.wd;h.setSkinObject=h.qh;h.changeViewMode=h.Od;h.getViewMode=h.je;h.changePolygonMode=h.Nd;h.setPolygonMode=h.Nd;h.getPolygonMode=h.sg;h.showOnePolyHotspot=h.Xe;h.hideOnePolyHotspot=h.me;h.changePolyHotspotColor=h.Ef;h.setPolyHotspotHandcursor=h.oh;h.toggleOnePolyHotspot=h.Lh;h.changeViewState=h.Bc;h.getViewState=h.ke;h.isTouching=h.Ig;h.getIsMobile=h.bg;h.setIsMobile=h.kh;h.getHasTouch=h.be;h.getIsAutorotating=h.Zf;h.getIsLoading=h.ag;h.getIsLoaded=h.$f;h.getIsTileLoading=
h.cg;h.getLastActivity=h.eg;h.getPan=h.Vb;h.getPanN=h.ng;h.getPanNorth=h.og;h.getPanDest=h.mg;h.setPan=h.ld;h.changePan=h.zc;h.changePanLog=h.Df;h.getTilt=h.ie;h.getTiltDest=h.yg;h.setTilt=h.md;h.changeTilt=h.Ac;h.changeTiltLog=h.Ff;h.getFov=h.hb;h.setFov=h.Nb;h.changeFov=h.xc;h.changeFovLog=h.yc;h.setPanTiltFov=h.nh;h.getZoom=h.Ag;h.setZoom=h.eb;h.changeZoom=h.Hf;h.getHasZoom=h.Xf;h.showObjectImage=h.We;h.setDefaultView=h.Oe;h.getX=h.getX;h.getY=h.getY;h.setX=h.setX;h.setY=h.setY;h.setXY=h.setXY;
h.setXYZoom=h.vh;h.getState=h.getState;h.getStateTitle=h.wg;h.getColumnsCount=h.Mc;h.getRowsCount=h.Oc;h.getStatesCount=h.xg;h.canPanRight=h.Kd;h.canPanLeft=h.Jd;h.canTiltUp=h.Md;h.canTiltDown=h.Ld;h.canZoomIn=h.Bf;h.canZoomOut=h.Cf;h.setLocked=h.setLocked;h.setLockedMouse=h.Se;h.setLockedKeyboard=h.Re;h.getLockedKeyboard=h.fg;h.setLockedWheel=h.Te;h.moveTo=h.moveTo;h.moveToEx=h.Ng;h.moveToDefaultView=h.Ge;h.moveToDefaultViewEx=h.Mg;h.moveToXYZoom=h.dd;h.playSound=h.jc;h.playPauseSound=h.Je;h.playStopSound=
h.Ke;h.pauseSound=h.fd;h.activateSound=h.vf;h.soundGetTime=h.Ah;h.soundSetTime=h.Ch;h.soundSetPlaybackRate=h.Bh;h.setMediaVisibility=h.mh;h.isPlaying=h.isPlaying;h.stopSound=h.od;h.setVolume=h.setVolume;h.changeVolume=h.Gf;h.mute=h.Qg;h.unmute=h.Sh;h.toggleMuted=h.Kh;h.getPlayerMuted=h.qg;h.getHasSounds=h.Wf;h.getSoundsPermitted=h.ug;h.startAutoplayMedia=h.Eh;h.removeHotspots=h.ah;h.getHotspotsVisible=h.Yf;h.getHotspotPropValue=h.de;h.setHotspotPropValue=h.Pe;h.getCustomPropertyDefaultValue=h.Vf;
h.addHotspot=h.wf;h.updateHotspot=h.Uh;h.removeHotspot=h.$g;h.getPointHotspotIds=h.rg;h.getHotspot=h.ce;h.setFullscreen=h.cb;h.toggleFullscreen=h.qc;h.enterFullscreen=h.Nf;h.exitFullscreen=h.exitFullscreen;h.getIsFullscreen=h.ee;h.startAutorotate=h.Ze;h.stopAutorotate=h.af;h.toggleAutorotate=h.hf;h.pauseAutorotate=h.Ug;h.resumeAutorotate=h.dh;h.setAutorotateNodeFilter=h.fh;h.createLayers=h.Dc;h.getScreenResolution=h.he;h.getMaxScreenResolution=h.gg;h.getCurrentPointHotspots=h.Uf;h.setElementIdPrefix=
h.ih;h.getMediaObject=h.fe;h.getMediaBufferSourceObject=h.hg;h.registerVideoElement=h.Zg;h.disableSoundLoading=h.Ud;h.setCrossOrigin=h.setCrossOrigin;h.addVariable=h.yf;h.setVariableOptions=h.Ve;h.setVariableValue=h.mc;h.getVariableValue=h.zg;h.setSuperCookie=h.th;h.getOS=h.lg;h.getBrowser=h.Sf;h.getBrowserTheme=h.Tf;h.triggerEvent=h.u;h.requestRedraw=h.bh;h.getHasTouch=h.be;h.updateViewerSizeNow=h.wd;h.getApiVersion=h.Rf;h.setApiVersion=h.eh;h.getZoomCenterCursor=h.Bg;h.setZoomCenterCursor=h.wh;
h.getPlayerState=h.ge;h.setPlayerState=h.Ue;h.getQueryParameter=h.getQueryParameter;h.setQueryParameter=h.ph;h.getNodeUserdata=h.kg;h.setActiveHotspot=h.bb})();
